### ISSUE TITLE
Investigate  "Cannot read property 'log' of undefined" from auto-label logs

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/repo-automation-bots#1135]
I have no idea how this is happening, but I'm seeing this in the logs only for auto-label:

```
TypeError: Cannot read property 'log' of undefined
        at error (/workspace/node_modules/gcf-utils/build/src/logging/gcf-logger.js:43:14)
        at runMicrotasks (<anonymous>)
        at async Function.addLabeltoRepoAndIssue (/workspace/build/src/auto-label.js:207:9)
        at async /workspace/build/src/auto-label.js:299:13
        at async Promise.all (index 0)
        at async Promise.all (index 0)
        at async /workspace/node_modules/gcf-utils/build/src/gcf-utils.js:172:21
```

What's wild is that stack trace refers to this code:

```js
info(objOrMsg, addMsg, ...args) {
  this.log('info', objOrMsg, addMsg, ...args);
}
```

Inside this object:
```js
class GCFLogger {
    constructor(customDestination) {
        this.initPinoLogger(customDestination);
        this.trace = this.trace.bind(this);
        this.debug = this.debug.bind(this);
        this.info = this.info.bind(this);
        this.warn = this.warn.bind(this);
        this.metric = this.metric.bind(this);
        this.error = this.error.bind(this);
    }
    info(objOrMsg, addMsg, ...args) {
        this.log('info', objOrMsg, addMsg, ...args);
    }
  // .... more stuff
}
```

With the bind happening in the constructor, my brain has no idea how in the world `this` is undefined inside of the `info` function.  Yet there it is.  In the logs. 

Is it possible the usage here is bad?  (from compiled code)

```js
await context.github.issues
            .createLabel({
            owner,
            repo,
            name: 'samples',
            color: colors_json_1.default[colorNumber].color,
        })
       .catch(gcf_utils_1.logger.error);
```

@bcoe if you pass a function reference like this, does it mess with the scope?

**Comment by bcoe** [comment]
👋 I believe this is addressed now?

**Comment by JustinBeckwith** [comment]
Yup - wanted to give a little time for the logs to work through, but I think we're set now :)
