### ISSUE TITLE
bug(release-please): HttpError: Validation Failed

### ISSUE THREAD

**Issue by tmatsuo** [googleapis/repo-automation-bots#1637]
Here is the stack trace:
```
    HttpError: Validation Failed: {"resource":"Release","code":"already_exists","field":"tag_name"}
        at /workspace/node_modules/@octokit/request/dist-node/index.js:66:23
        at runMicrotasks (<anonymous>)
        at async sendRequestWithRetries (/workspace/node_modules/@octokit/auth-app/dist-node/index.js:445:12)
        at async GitHub.createRelease (/workspace/node_modules/release-please/build/src/github.js:1031:17)
        at async GitHubRelease.createRelease (/workspace/node_modules/release-please/build/src/github-release.js:36:29)
        at async GitHubRelease.run (/workspace/node_modules/release-please/build/src/github-release.js:45:38)
        at async Function.Runner.releaser (/workspace/build/src/runner.js:24:5)
        at async createGitHubRelease (/workspace/build/src/release-please.js:96:9)
        at async /workspace/build/src/release-please.js:165:13 
```

**Comment by tmatsuo** [comment]
It seems that someone is trying to release twice.

**Comment by chingor13** [comment]
We should probably open an issue on the affected repository, referencing the release PR that is trying to tag a new release

**Comment by tmatsuo** [comment]
I think it's a private repo, and I can not access.

**Comment by chingor13** [comment]
In https://github.com/googleapis/release-please/releases/tag/v11.14.0, we are catching this scenario and throwing a `DuplicateReleaseError`. This should make it easier to catch this scenario and handle appropriately.
