### ISSUE TITLE
OwlBot is not currently copying changes from googleapis-gen to repositories

### ISSUE THREAD

**Issue by bcoe** [googleapis/repo-automation-bots#1738]
We are receiving this error when `scanGoogleapisGenAndCreatePullRequests` is run:

```
Step #3: (node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Step #3: (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
Step #3: (Use `node --trace-warnings ...` to show where the warning was created)
Step #3:     at processTicksAndRejections (internal/process/task_queues.js:93:5)
Step #3:     at runMicrotasks (<anonymous>)
Step #3:     at Object.scanGoogleapisGenAndCreatePullRequests (/usr/src/app/build/src/scan-googleapis-gen-and-create-pull-requests.js:102:27)
Step #3:     at Object.copyCodeAndCreatePullRequest (/usr/src/app/build/src/copy-code.js:77:5)
Step #3:     at cmd (/usr/src/app/build/src/cmd.js:40:21)
Step #3:     at Object.execSync (child_process.js:652:15)
Step #3:     at checkExecSyncError (child_process.js:616:11)
Step #3: 
Step #3: fatal: could not read Username for 'https://github.com': No such device or address
Step #3: Cloning into '/tmp/tmp-1-gcyc1jryQCMx/dest'...
Step #3: (node:1) UnhandledPromiseRejectionWarning: Error: Command failed: git clone --single-branch "https://github.com/googleapis/java-essential-contacts.git" /tmp/tmp-1-gcyc1jryQCMx/dest
Step #3: fatal: could not read Username for 'https://github.com': No such device or address
Step #3: Cloning into '/tmp/tmp-1-gcyc1jryQCMx/dest'...
Step #3: git clone --single-branch "https://github.com/googleapis/java-essential-contacts.git" /tmp/tmp-1-gcyc1jryQCMx/dest
Step #3: Working in /tmp/tmp-1-gcyc1jryQCMx
Step #3: 104 items in the todo stack.
Step #3: Done searching through commit history.
```

To me it looks like a parsing issue with the new URL helpers potentially.

**Comment by SurferJeffAtGoogle** [comment]
Looking at it....
