### ISSUE TITLE
bug(release-please): release-please crashes with `TypeError: config.branches.find is not a function`

### ISSUE THREAD

**Issue by tmatsuo** [googleapis/repo-automation-bots#1781]
It seems happening for `googleapis/java-compute`
```
    TypeError: config.branches.find is not a function
        at findBranchConfiguration (/workspace/build/src/release-please.js:63:35)
        at /workspace/build/src/release-please.js:155:37
        at runMicrotasks (<anonymous>)
        at async Promise.all (index 0)
        at async /workspace/node_modules/gcf-utils/build/src/gcf-utils.js:228:21
```

**Comment by tmatsuo** [comment]
Bumped to p1 cos' it's happening many times.
