### ISSUE TITLE
test fails when run locally: GCFBootstrapper, gcf, fetches payload from Cloud Storage, if tmpUrl in payload

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [googleapis/repo-automation-bots#1803]
@sofisl and I both observed the same error when we tried running the test locally:

```
  1 failing

  1) GCFBootstrapper
       gcf
         fetches payload from Cloud Storage, if tmpUrl in payload:
     AssertError: expected stub to be called once but was called 0 times
      at Object.fail (node_modules\sinon\lib\sinon\assert.js:120:25)
      at failAssertion (node_modules\sinon\lib\sinon\assert.js:66:20)
      at Object.assert.<computed> [as calledOnce] (node_modules\sinon\lib\sinon\assert.js:95:17)
      at Context.<anonymous> (build\test\gcf-bootstrapper.js:239:36)
          -> C:\Users\rennie\gitrepos\repo-automation-bots\packages\gcf-utils\test\gcf-bootstrapper.ts:269:20
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by chingor13** [comment]
I fixed this in once of my gcf-utils features because it was annoying me.
