### ISSUE TITLE
bug(auto-label): crashes for installation to personal org (it seems like)

### ISSUE THREAD

**Issue by tmatsuo** [googleapis/repo-automation-bots#1816]
I could not get any logs, but I know this from the Cloud task retries.

@jjnanthakumar 
I think you're trying to install auto-label bot. Let me know if this is not the case.

These bots (except for release-please) are primarily for Google managed repositories, and we don't support external use cases.
Sorry for the confusion.

**Comment by tmatsuo** [comment]
@tbpg FYI

I'd keep this issue open in case we want to debug more.

**Comment by tmatsuo** [comment]
I managed to get the stack trace:

```
    HttpError: Not Found
        at /workspace/node_modules/@octokit/request/dist-node/index.js:68:23
        at runMicrotasks (<anonymous>)
        at async getInstallationAuthentication (/workspace/node_modules/@octokit/auth-app/dist-node/index.js:261:7)
        at async hook (/workspace/node_modules/@octokit/auth-app/dist-node/index.js:420:7)
        at async Object.next (/workspace/node_modules/@octokit/plugin-paginate-rest/dist-node/index.js:62:26)
        at async /workspace/build/src/auto-label.js:343:30
        at async Promise.all (index 0)
        at async /workspace/node_modules/gcf-utils/build/src/gcf-utils.js:228:21"
```

**Comment by tmatsuo** [comment]
We haven't seem this error for a long time (I think), closing.
