### ISSUE TITLE
bug(auto-label): scheduled job failed with server error

### ISSUE THREAD

**Issue by tmatsuo** [googleapis/repo-automation-bots#1848]
Log:
```
    HttpError: Server Error
        at /workspace/node_modules/@octokit/request/dist-node/index.js:68:23
        at async getInstallationAuthentication (/workspace/node_modules/@octokit/auth-app/dist-node/index.js:261:7)
        at async hook (/workspace/node_modules/@octokit/auth-app/dist-node/index.js:420:7)
        at async getConfigFile (/workspace/node_modules/@probot/octokit-plugin-config/dist-node/index.js:103:9)
        at async getConfigFiles (/workspace/node_modules/@probot/octokit-plugin-config/dist-node/index.js:203:29)
        at async composeConfigGet (/workspace/node_modules/@probot/octokit-plugin-config/dist-node/index.js:283:17)
        at async Context.config (/workspace/node_modules/probot/lib/context.js:157:35)
        at async /workspace/build/src/auto-label.js:232:24
        at async Promise.all (index 0)"
```
execution_id: "tm6nrsybfmth"

Probably intermittent error because gcp job suceeded.

**Comment by tmatsuo** [comment]
Manually retried googleapis job

**Comment by tmatsuo** [comment]
Still failing.

I think I found an error log for the first failure:

```
HttpError: Server Error at /workspace/node_modules/@octokit/request/dist-node/index.js:68:23 at async getInstallationAuthentication (/workspace/node_modules/@octokit/auth-app/dist-node/index.js:261:7) at async hook (/workspace/node_modules/@octokit/auth-app/dist-node/index.js:420:7) at async getConfigFile (/workspace/node_modules/@probot/octokit-plugin-config/dist-node/index.js:103:9) at async getConfigFiles (/workspace/node_modules/@probot/octokit-plugin-config/dist-node/index.js:203:29) at async composeConfigGet (/workspace/node_modules/@probot/octokit-plugin-config/dist-node/index.js:283:17) at async Context.config (/workspace/node_modules/probot/lib/context.js:157:35) at async /workspace/build/src/auto-label.js:232:24 at async Promise.all (index 0)
```

**Comment by tmatsuo** [comment]
I think we can close this.
