### ISSUE TITLE
bug: failed to update package-lock.json for some packages

### ISSUE THREAD

**Issue by tmatsuo** [googleapis/repo-automation-bots#1977]
- [x] gcf-utils: 'npm i' failed
- [ ] owl-bot: 'npm run test' failed

gcf-utils-npm-i.log:
```
> gcf-utils@8.0.1 prepare /usr/local/google/home/tmatsuo/work/repo-automation-bots/packages/gcf-utils
> npm run compile


> gcf-utils@8.0.1 compile /usr/local/google/home/tmatsuo/work/repo-automation-bots/packages/gcf-utils
> tsc -p .

^[[96mnode_modules/octokit-auth-probot/dist-types/types.d.ts^[[0m:^[[93m14^[[0m:^[[93m75^[[0m - ^[[91merror^[[0m^[[90m TS2694: ^[[0mNamespace '"/usr/local/google/\
home/tmatsuo/work/repo-automation-bots/packages/gcf-utils/node_modules/@octokit/auth-app/dist-types/index"' has no exported member 'AuthOptions'.

^[[7m14^[[0m export declare type AuthOptions = TokenAuthTypes["AuthOptions"] | AppAuth.AuthOptions | {
^[[7m  ^[[0m ^[[91m                                                                          ~~~~~~~~~~~^[[0m


Found 1 error.

```

owl-bot-npm-run-test.log
```
  1) copyDirs
       works for real java tree:
     TypeError: fs.rmSync is not a function
      at Object.copyDirs (build/src/copy-code.js:249:16)
          -> /usr/local/google/home/tmatsuo/work/repo-automation-bots/packages/owl-bot/src/copy-code.ts:287:10
      at Context.<anonymous> (build/test/copy-code.js:161:21)
          -> /usr/local/google/home/tmatsuo/work/repo-automation-bots/packages/owl-bot/test/copy-code.ts:155:5
      at processImmediate (internal/timers.js:456:21)

```

**Comment by tmatsuo** [comment]
For gcf-utils log, it is better if we can disable color for `npm run compile` or `tsc` for better output.

**Comment by sofisl** [comment]
@tmatsuo, I think this is worth closing since we were able to update the lock file eventually? (#2001)

**Comment by tmatsuo** [comment]
Not yet for owl-bot, so maybe assign it to @SurferJeffAtGoogle ?

**Comment by tmatsuo** [comment]
Dup
