### ISSUE TITLE
bug(policy): crashes with HTTPError "Branch not found"

### ISSUE THREAD

**Issue by tmatsuo** [googleapis/repo-automation-bots#1989]
```
"HttpError: Branch not found
    at /workspace/node_modules/@octokit/request/dist-node/index.js:76:23
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async sendRequestWithRetries (/workspace/node_modules/@octokit/auth-app/dist-node/index.js:450:12)
    at async getBranchHead (/workspace/node_modules/code-suggester/build/src/github/branch.js:37:25)
    at async Object.branch (/workspace/node_modules/code-suggester/build/src/github/branch.js:107:25)
    at async retry.retries (/workspace/node_modules/code-suggester/build/src/index.js:105:48)
    at async Object.createPullRequest (/workspace/node_modules/code-suggester/build/src/index.js:105:24)
    at async Changer.addFile (/workspace/build/src/changer.js:94:9)
    at async Changer.submitFixes (/workspace/build/src/changer.js:114:13)"
```

I think we can ignore such cases.

**Comment by bcoe** [comment]
@JustinBeckwith is @tmatsuo right that we can skip suppress this error?

**Comment by JustinBeckwith** [comment]
I mean it kinda depends on where it is

**Comment by sofisl** [comment]
This will be OOSLO soon.
