### ISSUE TITLE
bug(canary-bot): crashes with NotFound

### ISSUE THREAD

**Issue by tmatsuo** [googleapis/repo-automation-bots#2003]
```
HttpError: Not Found
        at /workspace/node_modules/@octokit/request/dist-node/index.js:76:23
        at async sendRequestWithRetries (/workspace/node_modules/@octokit/auth-app/dist-node/index.js:450:12)
        at async /workspace/build/src/canary-bot.js:42:13
        at async Promise.all (index 0)
        at async /workspace/node_modules/gcf-utils/build/src/gcf-utils.js:228:21 
```

**Comment by tmatsuo** [comment]
I guess the bot is using a wrong `owner` from `context.payload.issue.user.login`. I think it works for installation for personal repositories, but doesn't work for organization installation.
