### ISSUE TITLE
Using owl-bot to generate a new library

### ISSUE THREAD

**Issue by sofisl** [googleapis/repo-automation-bots#2037]
I'm using owl-bot to generate a new library, `connect-gateway`. I'm using the same process I've used to generate other libraries ([here](go/yoshi-nodejs-playbook#generate)), but when I run this command, I get into this issue:

`docker run  --user $(id -u):$(id -g) --rm -v $(pwd):/repo -w /repo gcr.io/repo-automation-bots/owlbot-nodejs:latest`

```
+ '[' -f owlbot.py ']'
+ python -m synthtool.languages.node
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/synthtool/synthtool/languages/node.py", line 373, in <module>
    owlbot_main()
  File "/synthtool/synthtool/languages/node.py", line 352, in owlbot_main
    versions = [v.name for v in src.iterdir() if v.is_dir()]
  File "/synthtool/synthtool/languages/node.py", line 352, in <listcomp>
    versions = [v.name for v in src.iterdir() if v.is_dir()]
  File "/usr/local/lib/python3.9/pathlib.py", line 1149, in iterdir
    for name in self._accessor.listdir(self):
FileNotFoundError: [Errno 2] No such file or directory: 'src'
```

This indicates that there's no source folder, even though the step before it finishes it successfully:

`docker run --rm --user $(id -u):$(id -g) -v $(pwd):/repo -w /repo gcr.io/repo-automation-bots/owlbot-cli:latest copy-code`

**Comment by SurferJeffAtGoogle** [comment]
What's the the output of `find . | grep -v ./git/` when run the docker command?

**Comment by sofisl** [comment]
Solved! This was an issue with the path in `.OwlBot.yaml`.
