### ISSUE TITLE
Failed to update package-lock.json for some packages.

### ISSUE THREAD

**Issue by tmatsuo** [googleapis/repo-automation-bots#2040]
- [ ] gcf-utils: 'npm i' with ncu failed
- [ ] owl-bot: 'npm run test' with ncu failed
- [ ] owl-bot: 'npm run test'  failed
- [ ] policy: 'npm run test' with ncu failed

For auto-approve and owl-bot, test failed both with or without the major bump.

For gcf-utils, `npm i` (and compile) failed with major bump, but it successfully update the package-lock.json without the major bump.

For policy, `npm run test` failed with major bump, but it successfully update the package-lock.json without the major bump.

**Comment by tmatsuo** [comment]
The failure log is too big, so created [a gist](https://gist.github.com/tmatsuo/751db2d4806394a6f5bd4800a7d625fb)

**Comment by tmatsuo** [comment]
I run the script again today. auto-approve is ok now.

Here are some relevant logs:

gcf-utils-npm-i-with-ncu.log
```

> gcf-utils@10.0.0 prepare /usr/local/google/home/tmatsuo/work/repo-automation-bots/packages/gcf-utils
> npm run compile


> gcf-utils@10.0.0 compile /usr/local/google/home/tmatsuo/work/repo-automation-bots/packages/gcf-utils
> tsc -p .

node_modules/@types/pino/index.d.ts:197:8 - error TS2709: Cannot use namespace 'SonicBoom' as a type.

197     ): SonicBoom;
           ~~~~~~~~~

node_modules/@types/pino/index.d.ts:205:57 - error TS2709: Cannot use namespace 'SonicBoom' as a type.

205     function extreme(fileDescriptor?: string | number): SonicBoom;
                                                            ~~~~~~~~~

src/bin/genkey.ts:63:22 - error TS2339: Property 'keyfile' does not exist on type '{ [x: string]: unknown; keyfile: string; verbose: boolean
; project: string; bot: string; id: string; secret: string; _: (string | number)[]; $0: string; } | Promise<{ [x: string]: unknown; keyfile: string; verbose: boolean; project:
 string; ... 4 more ...; $0: string; }>'.
  Property 'keyfile' does not exist on type 'Promise<{ [x: string]: unknown; keyfile: string; verbose: boolean; project: string; bot: string; id: string; secret: string; _: (s
tring | number)[]; $0: string; }>'.

63 const keyfile = argv.keyfile || 'key.pem';
                        ~~~~~~~

src/bin/genkey.ts:64:22 - error TS2339: Property 'project' does not exist on type '{ [x: string]: unknown; keyfile: string; verbose: boolean
; project: string; bot: string; id: string; secret: string; _: (string | number)[]; $0: string; } | Promise<{ [x: string]: unknown; keyfile: string; verbose: boolean; project:
 string; ... 4 more ...; $0: string; }>'.
  Property 'project' does not exist on type 'Promise<{ [x: string]: unknown; keyfile: string; verbose: boolean; project: string; bot: string; id: string; secret: string; _: (s
tring | number)[]; $0: string; }>'.

64 const project = argv.project as string;
                        ~~~~~~~

src/bin/genkey.ts:65:22 - error TS2339: Property 'bot' does not exist on type '{ [x: string]: unknown; keyfile: string; verbose: boolean; pr
oject: string; bot: string; id: string; secret: string; _: (string | number)[]; $0: string; } | Promise<{ [x: string]: unknown; keyfile: string; verbose: boolean; project: str
ing; ... 4 more ...; $0: string; }>'.
  Property 'bot' does not exist on type 'Promise<{ [x: string]: unknown; keyfile: string; verbose: boolean; project: string; bot: string; id: string; secret: string; _: (strin
g | number)[]; $0: string; }>'.

65 const botname = argv.bot!;
                        ~~~

src/bin/genkey.ts:66:28 - error TS2339: Property 'secret' does not exist on type '{ [x: string]: unknown; keyfile: string; verbose: boolean;
 project: string; bot: string; id: string; secret: string; _: (string | number)[]; $0: string; } | Promise<{ [x: string]: unknown; keyfile: string; verbose: boolean; project: 
string; ... 4 more ...; $0: string; }>'.
  Property 'secret' does not exist on type 'Promise<{ [x: string]: unknown; keyfile: string; verbose: boolean; project: string; bot: string; id: string; secret: string; _: (st
ring | number)[]; $0: string; }>'.

66 const webhookSecret = argv.secret;
                              ~~~~~~

src/bin/genkey.ts:67:24 - error TS2339: Property 'id' does not exist on type '{ [x: string]: unknown; keyfile: string; verbose: boolean; pro
ject: string; bot: string; id: string; secret: string; _: (string | number)[]; $0: string; } | Promise<{ [x: string]: unknown; keyfile: string; verbose: boolean; project: stri
ng; ... 4 more ...; $0: string; }>'.
  Property 'id' does not exist on type 'Promise<{ [x: string]: unknown; keyfile: string; verbose: boolean; project: string; bot: string; id: string; secret: string; _: (string
 | number)[]; $0: string; }>'.

67 const id = Number(argv.id);
                          ~~


Found 7 errors.
```

**Comment by tmatsuo** [comment]
owl-bot-npm-run-test-with-ncu.log
```
  1 failing

  1) copyDirs
       works for real java tree:
     TypeError: fs.rmSync is not a function
      at Object.copyDirs (build/src/copy-code.js:250:16)
          -> /usr/local/google/home/tmatsuo/work/repo-automation-bots/packages/owl-bot/src/copy-code.ts:288:10
      at Context.<anonymous> (build/test/copy-code.js:161:21)
          -> /usr/local/google/home/tmatsuo/work/repo-automation-bots/packages/owl-bot/test/copy-code.ts:155:5
      at processImmediate (internal/timers.js:456:21)

```

It fails without ncu with the same error too.

**Comment by tmatsuo** [comment]
policy-npm-run-test-with-ncu.log

```
> policy@1.0.0 pretest /usr/local/google/home/tmatsuo/work/repo-automation-bots/packages/policy
> npm run compile


> policy@1.0.0 compile /usr/local/google/home/tmatsuo/work/repo-automation-bots/packages/policy
> tsc -p .

src/cli.ts:45:3 - error TS2345: Argument of type '{ flags: { repo: { type: "string"; }; search: { type: "string"; }; autofix: { type: "boolean"; }; }; }' is not assignable to parameter of type 'Options<{ repo: { type: "string"; }; sea
rch: { type: "string"; }; autofix: { type: "boolean"; }; }>'.
  Property 'importMeta' is missing in type '{ flags: { repo: { type: "string"; }; search: { type: "string"; }; autofix: { type: "boolean"; }; }; }' but required in type 'Options<{ repo: { type: "string"; }; search: { type: "string"; }; autofix: { type: "boolean"; }; }>
'.

 45   {
      ~
 46     flags: {
    ~~~~~~~~~~~~
... 
 50     },
    ~~~~~~
 51   }
    ~~~

  node_modules/meow/index.d.ts:33:11
    33  readonly importMeta: ImportMeta;
                 ~~~~~~~~~~
    'importMeta' is declared here.

src/cli.ts:54:33 - error TS2503: Cannot find namespace 'meow'.

54 export async function main(cli: meow.Result<{}>) {
                                   ~~~~

test/test.cli.ts:35:21 - error TS2503: Cannot find namespace 'meow'.

35     const m = {} as meow.Result<{}>;
                       ~~~~

test/test.cli.ts:45:21 - error TS2503: Cannot find namespace 'meow'.

45     } as unknown as meow.Result<{}>;
                       ~~~~

test/test.cli.ts:64:21 - error TS2503: Cannot find namespace 'meow'.

64     } as unknown as meow.Result<{}>;
                       ~~~~

test/test.cli.ts:89:21 - error TS2503: Cannot find namespace 'meow'.

89     } as unknown as meow.Result<{}>;
                       ~~~~

test/test.cli.ts:110:21 - error TS2503: Cannot find namespace 'meow'.

110     } as unknown as meow.Result<{}>;
                        ~~~~


Found 7 errors.

```

**Comment by tmatsuo** [comment]
These errors except for owl-bot are well represented by the current open PRs from renovate:
#1643 
#1729 
#1846
