### ISSUE TITLE
bug(merge-on-green): SyncLabels cron scheduler dies with HttpError: This installation has been suspended

### ISSUE THREAD

**Issue by tmatsuo** [googleapis/repo-automation-bots#2157]
```
stack: "HttpError: This installation has been suspended
    at /workspace/node_modules/@octokit/request/dist-node/index.js:86:21
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async getInstallationAuthentication (/workspace/node_modules/@octokit/auth-app/dist-node/index.js:274:7)
    at async hook (/workspace/node_modules/@octokit/auth-app/dist-node/index.js:433:7)
    at async Object.next (/workspace/node_modules/@octokit/plugin-paginate-rest/dist-node/index.js:124:28)
    at async GCFBootstrapper.eachInstalledRepository (/workspace/node_modules/gcf-utils/build/src/gcf-utils.js:424:26)
    at async GCFBootstrapper.handleScheduledRepository (/workspace/node_modules/gcf-utils/build/src/gcf-utils.js:537:34)
    at async GCFBootstrapper.handleScheduled (/workspace/node_modules/gcf-utils/build/src/gcf-utils.js:377:13)
    at async /workspace/node_modules/gcf-utils/build/src/gcf-utils.js:289:21"
```

**Comment by bcoe** [comment]
@chingor13 perhaps only a p2 if this is an installation token that's not our own. If our own installation has been suspended, it seems to correlate with some of our refactoring.

**Comment by bcoe** [comment]
This can wait until after vacation, let's call P2 for now.
