### ISSUE TITLE
owl-bot frontend dies with "Error: 14 UNAVAILABLE: read ECONNRESET"

### ISSUE THREAD

**Issue by tmatsuo** [googleapis/repo-automation-bots#2265]
Starring as P2 because it's very rare.

The error log:
```
{
  "insertId": "60ed5b52000534eabd06fd2b",
  "jsonPayload": {
    "details": "read ECONNRESET",
    "message": "14 UNAVAILABLE: read ECONNRESET",
    "metadata": {
      "options": {},
      "internalRepr": {}
    },
    "code": 14,
    "type": "Error",
    "trigger": {
      "trigger_source_repo": {
        "owner_type": "Organization",
        "repo_name": "google-resumable-media-python",
        "url": "https://github.com/googleapis/google-resumable-media-python",
        "owner": "googleapis"
      },
      "trigger_sender": "gcf-merge-on-green[bot]",
      "github_event_type": "pull_request.unlabeled",
      "github_delivery_guid": "d602a860-e3bb-11eb-9f5f-01f9e172f02b",
      "trigger_type": "GitHub Webhook",
      "payload_hash": "c4d522aac65d2bb87ffdecd9f7c49869"
    },
    "level": 50,
    "stack": "Error: 14 UNAVAILABLE: read ECONNRESET\n    at Object.callErrorFromStatus (/usr/src/app/node_modules/@grpc/grpc-js/build/src/call.js:31:26)\n    at Object.onReceiveStatus (/usr/src/app/node_modules/@grpc/grpc-js/build/src/client.js:179:52)\n    at Object.onReceiveStatus (/usr/src/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:336:141)\n    at Object.onReceiveStatus (/usr/src/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:299:181)\n    at /usr/src/app/node_modules/@grpc/grpc-js/build/src/call-stream.js:145:78\n    at processTicksAndRejections (internal/process/task_queues.js:77:11)"
  },
  "resource": {
    "type": "cloud_run_revision",
    "labels": {
      "project_id": "repo-automation-bots",
      "revision_name": "owl-bot-00007-zag",
      "location": "us-central1",
      "configuration_name": "owl-bot",
      "service_name": "owl-bot"
    }
  },
  "timestamp": "2021-07-13T09:22:26.341226Z",
  "severity": "ERROR",
  "labels": {
    "instanceId": "00bf4bf02d480c07e7ac82c2a94eedcb21772fc9b421079001923328aadc9c17206d6cbdd09c42e99eaf03bbfd7759770d2a1010e3d0dd86a84eb0f6ed"
  },
  "logName": "projects/repo-automation-bots/logs/run.googleapis.com%2Fstdout",
  "receiveTimestamp": "2021-07-13T09:22:26.409211893Z"
}
```

**Comment by tmatsuo** [comment]
Actually it happened 4 times today.

If we regularly see the same error, we should prioritize fixing this.

**Comment by SurferJeffAtGoogle** [comment]
When this happens, what are the consequences?  Does Owl Bot not run for a pull request that it should have?

**Comment by tmatsuo** [comment]
It drops the webhook

**Comment by SurferJeffAtGoogle** [comment]
Does the webhook get retried?  If not, downstream, what are the consequences?

**Comment by tmatsuo** [comment]
It's not retried

**Comment by tmatsuo** [comment]
The event will be lost.

For those 4 cases, all the events are harmless jfyi

**Comment by SurferJeffAtGoogle** [comment]
Cool, that's what I'm looking for: the harm or absence of harm.  Network failures are to be expected and coped with.  They only become an issue if we don't cope with them.
