### ISSUE TITLE
owl-bot fails to get the cloud build result and submits a failure status

### ISSUE THREAD

**Issue by tmatsuo** [googleapis/repo-automation-bots#2268]
It seems like the bot failed to get the build status because of a quota error:

```
Quota exceeded for quota metric 'Build and Operation Get requests' and limit 'Build and Operation Get requests per minute' of service 'cloudbuild.googleapis.com' for consumer 'project_number:xxxxxxxxxxxx'.",
    "stack": "Error: 8 RESOURCE_EXHAUSTED: Quota exceeded for quota metric 'Build and Operation Get requests' and limit 'Build and Operation Get requests per minute' of service 'cloudbuild.googleapis.com' for consumer 'project_number:xxxxxxxxxxxx'.\n    at Object.callErrorFromStatus (/workspace/node_modules/@grpc/grpc-js/build/src/call.js:31:26)\n    at Object.onReceiveStatus (/workspace/node_modules/@grpc/grpc-js/build/src/client.js:179:52)\n    at Object.onReceiveStatus (/workspace/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:336:141)\n    at Object.onReceiveStatus (/workspace/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:299:181)\n    at /workspace/node_modules/@grpc/grpc-js/build/src/call-stream.js:145:78\n    at processTicksAndRejections (internal/process/task_queues.js:79:11)
```

**Comment by tmatsuo** [comment]
We should bump the quota if possible.

**Comment by tmatsuo** [comment]
- bump the quota if possible
- polling less often at https://github.com/googleapis/repo-automation-bots/blob/6ec778c4cb0cc8a07566470554445dc293815c80/packages/owl-bot/src/core.ts#L179
- use the built-in longrunning operation. It seems like it doesn't work according to: https://github.com/googleapis/repo-automation-bots/blob/6ec778c4cb0cc8a07566470554445dc293815c80/packages/owl-bot/src/core.ts#L136

**Comment by tmatsuo** [comment]
Related: https://github.com/googleapis/gapic-generator-typescript/issues/928

**Comment by SurferJeffAtGoogle** [comment]
I don't think we've seen this in a while.  tmatsuo@ please re-open if it's still an issue.
