### ISSUE TITLE
bug(owl-bot): generation error

### ISSUE THREAD

**Issue by sofisl** [googleapis/repo-automation-bots#2308]
```
Already have image (with digest): gcr.io/repo-automation-bots/owlbot-java:latest@sha256:2904b9ad921ecc1343d1cf815bfaafbcc1115c1f39593aef9f8e333ffda552f7
Generating templates...
2021-07-27 15:37:04,549 synthtool [CRITICAL] > You are running the synthesis script directly, this will be disabled in a future release of Synthtool. Please use python3 -m synthtool instead.
Traceback (most recent call last):
  File "owlbot.py", line 24, in <module>
    java.common_templates()
  File "/synthtool/synthtool/languages/java.py", line 486, in common_templates
    kwargs["metadata"] = _common_template_metadata()
  File "/synthtool/synthtool/languages/java.py", line 461, in _common_template_metadata
    metadata["samples"] = samples.all_samples(["samples/**/src/main/java/**/*.java"])
  File "/synthtool/synthtool/gcp/samples.py", line 72, in all_samples
    return [_sample_metadata(file) for file in sorted(files)]
  File "/synthtool/synthtool/gcp/samples.py", line 72, in <listcomp>
    return [_sample_metadata(file) for file in sorted(files)]
  File "/synthtool/synthtool/gcp/samples.py", line 51, in _sample_metadata
    return {**metadata, **_read_sample_metadata_comment(file)}
  File "/synthtool/synthtool/gcp/samples.py", line 40, in _read_sample_metadata_comment
    sample_metadata = yaml.load(sample_metadata_string, Loader=yaml.SafeLoader)[
  File "/root/.pyenv/versions/3.6.12/lib/python3.6/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/root/.pyenv/versions/3.6.12/lib/python3.6/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/root/.pyenv/versions/3.6.12/lib/python3.6/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/root/.pyenv/versions/3.6.12/lib/python3.6/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/root/.pyenv/versions/3.6.12/lib/python3.6/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/root/.pyenv/versions/3.6.12/lib/python3.6/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/root/.pyenv/versions/3.6.12/lib/python3.6/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/root/.pyenv/versions/3.6.12/lib/python3.6/site-packages/yaml/parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "/root/.pyenv/versions/3.6.12/lib/python3.6/site-packages/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/root/.pyenv/versions/3.6.12/lib/python3.6/site-packages/yaml/scanner.py", line 173, in fetch_more_tokens
    return self.fetch_stream_end()
  File "/root/.pyenv/versions/3.6.12/lib/python3.6/site-packages/yaml/scanner.py", line 377, in fetch_stream_end
    self.remove_possible_simple_key()
  File "/root/.pyenv/versions/3.6.12/lib/python3.6/site-packages/yaml/scanner.py", line 319, in remove_possible_simple_key
    "could not find expected ':'", self.get_mark())
yaml.scanner.ScannerError: while scanning a simple key
  in "<unicode string>", line 5, column 1:
    -PmainClass=com.google.cloud.exa ... 
    ^
could not find expected ':'
  in "<unicode string>", line 5, column 84:
     ... 1beta1.SampleListRecommendations
```

https://pantheon.corp.google.com/cloud-build/builds;region=global/64f3a721-9fbc-4305-8029-bec57e8463c2;step=9?project=repo-automation-bots

**Comment by sofisl** [comment]
Same error again: https://pantheon.corp.google.com/cloud-build/builds;region=global/64f3a721-9fbc-4305-8029-bec57e8463c2?project=repo-automation-bots

**Comment by SurferJeffAtGoogle** [comment]
This issue is specific to java-recommender.  I filed https://github.com/googleapis/java-recommender/issues/554
