### ISSUE TITLE
Cloud Scheduler Job owl-bot-sync-label failed

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [googleapis/repo-automation-bots#2322]
![image](https://user-images.githubusercontent.com/11778530/127916920-f6ed91c1-3a87-4a11-8619-b526df8d7073.png)

**Comment by tmatsuo** [comment]
The timestamp of the scheduler failed request:

```
timestamp: "2021-08-02T10:12:28.341721532Z"
```

**Comment by tmatsuo** [comment]
The log in the Cloud Function side:

```
{
  "insertId": "000000-340c7799-2dcb-4f5e-866f-ad08a37da935",
  "jsonPayload": {
    "request": {
      "method": "GET",
      "headers": {
        "accept": "application/vnd.github.machine-man-preview+json",
        "authorization": "token [REDACTED]",
        "user-agent": "octokit-rest.js/18.6.7 octokit-core.js/3.5.1 Node.js/12.22.1 (linux; x64)"
      },
      "request": {},
      "url": "https://api.github.com/installation/repositories?page=19"
    },
    "name": "HttpError",
    "stack": "HttpError: request to https://api.github.com/installation/repositories?page=19 failed, reason: connect ETIMEDOUT 140.82.112.6:443\n    at /workspace/node_modules/@octokit/request/dist-node/index.js:108:11\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at async sendRequestWithRetries (/workspace/node_modules/@octokit/auth-app/dist-node/index.js:454:12)\n    at async Object.next (/workspace/node_modules/@octokit/plugin-paginate-rest/dist-node/index.js:124:28)\n    at async GCFBootstrapper.eachInstalledRepository (/workspace/node_modules/gcf-utils/build/src/gcf-utils.js:475:26)\n    at async GCFBootstrapper.handleScheduledRepository (/workspace/node_modules/gcf-utils/build/src/gcf-utils.js:588:34)\n    at async GCFBootstrapper.handleScheduled (/workspace/node_modules/gcf-utils/build/src/gcf-utils.js:423:13)\n    at async /workspace/node_modules/gcf-utils/build/src/gcf-utils.js:332:21",
    "level": 50,
    "trigger": {
      "trigger_type": "Cloud Scheduler"
    },
    "message": "request to https://api.github.com/installation/repositories?page=19 failed, reason: connect ETIMEDOUT 140.82.112.6:443",
    "type": "Error",
    "status": 500
  },
  "resource": {
    "type": "cloud_function",
    "labels": {
      "region": "us-central1",
      "function_name": "owl_bot",
      "project_id": "repo-automation-bots"
    }
  },
  "timestamp": "2021-08-02T10:12:28.321Z",
  "severity": "ERROR",
  "labels": {
    "execution_id": "ewksrssdooyq"
  },
  "logName": "projects/repo-automation-bots/logs/cloudfunctions.googleapis.com%2Fcloud-functions",
  "trace": "projects/repo-automation-bots/traces/02929efd3e6da31f701968baf8f0c139",
  "receiveTimestamp": "2021-08-02T10:12:39.338423516Z"
}
```

**Comment by tmatsuo** [comment]
It's also a transient error due to Github API timeout.

**Comment by bcoe** [comment]
Job ran well all last week, I think this was a transient issue like @tmatsuo says.
