### ISSUE TITLE
Cloud Scheduler Job sync_repo_settings failed

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [googleapis/repo-automation-bots#2324]
![image](https://user-images.githubusercontent.com/11778530/127917243-9b3ea990-a612-4ee8-a5ee-ea4b2c23cc7c.png)

**Comment by tmatsuo** [comment]
```
{
  "insertId": "ld733mg1jg3njd",
  "jsonPayload": {
    "targetType": "HTTP",
    "jobName": "projects/repo-automation-bots/locations/us-central1/jobs/sync_repo_settings",
    "status": "INTERNAL",
    "url": "https://serverless-scheduler-proxy-c7mcaca6sa-uc.a.run.app/v0",
    "@type": "type.googleapis.com/google.cloud.scheduler.logging.AttemptFinished"
  },
  "httpRequest": {
    "status": 500
  },
  "resource": {
    "type": "cloud_scheduler_job",
    "labels": {
      "project_id": "repo-automation-bots",
      "job_id": "sync_repo_settings",
      "location": "us-central1"
    }
  },
  "timestamp": "2021-08-02T08:02:18.668627620Z",
  "severity": "ERROR",
  "logName": "projects/repo-automation-bots/logs/cloudscheduler.googleapis.com%2Fexecutions",
  "receiveTimestamp": "2021-08-02T08:02:18.668627620Z"
}
```

**Comment by tmatsuo** [comment]
Then the Cloud Functions log:

```
{
  "insertId": "000000-81867380-e23e-4ed0-ad48-ccb411254d77",
  "jsonPayload": {
    "name": "HttpError",
    "message": "request to https://api.github.com/installation/repositories?page=7 failed, reason: connect ETIMEDOUT 140.82.112.6:443",
    "trigger": {
      "trigger_type": "Cloud Scheduler"
    },
    "type": "Error",
    "status": 500,
    "stack": "HttpError: request to https://api.github.com/installation/repositories?page=7 failed, reason: connect ETIMEDOUT 140.82.112.6:443\n    at /workspace/node_modules/@octokit/request/dist-node/index.js:108:11\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at async sendRequestWithRetries (/workspace/node_modules/@octokit/auth-app/dist-node/index.js:454:12)\n    at async Object.next (/workspace/node_modules/@octokit/plugin-paginate-rest/dist-node/index.js:124:28)\n    at async GCFBootstrapper.eachInstalledRepository (/workspace/node_modules/gcf-utils/build/src/gcf-utils.js:475:26)\n    at async GCFBootstrapper.handleScheduledRepository (/workspace/node_modules/gcf-utils/build/src/gcf-utils.js:553:30)\n    at async GCFBootstrapper.handleScheduled (/workspace/node_modules/gcf-utils/build/src/gcf-utils.js:423:13)\n    at async /workspace/node_modules/gcf-utils/build/src/gcf-utils.js:332:21",
    "request": {
      "url": "https://api.github.com/installation/repositories?page=7",
      "request": {},
      "method": "GET",
      "headers": {
        "accept": "application/vnd.github.machine-man-preview+json",
        "user-agent": "octokit-rest.js/18.6.8 octokit-core.js/3.5.1 Node.js/12.22.1 (linux; x64)",
        "authorization": "token [REDACTED]"
      }
    },
    "level": 50
  },
  "resource": {
    "type": "cloud_function",
    "labels": {
      "region": "us-central1",
      "function_name": "sync_repo_settings",
      "project_id": "repo-automation-bots"
    }
  },
  "timestamp": "2021-08-02T08:02:18.629Z",
  "severity": "ERROR",
  "labels": {
    "execution_id": "4ii90qemwy4j"
  },
  "logName": "projects/repo-automation-bots/logs/cloudfunctions.googleapis.com%2Fcloud-functions",
  "trace": "projects/repo-automation-bots/traces/36e0def3121ffb382141c73c90fbd9d4",
  "receiveTimestamp": "2021-08-02T08:02:28.723308463Z"
}
```

**Comment by tmatsuo** [comment]
Likely it's a transient error.

**Comment by tmatsuo** [comment]
I think we can close this. We haven't seen this for a while.
