### ISSUE TITLE
release-brancher does not work with repositories with "master" default branch

### ISSUE THREAD

**Issue by suztomo** [googleapis/repo-automation-bots#2617]
The release-brancher command-line tool fails with trying to create non-existent 'main' branch of my repository (https://api.github.com/repos/suztomo/google-http-java-client/branches/main). The default branch of the repository is "master".

```
suztomo-macbookpro44% release-brancher create-pull-request --branch-name="1.40.0-sp.2" --target-tag="v1.40.0" --repo="suztomo/google-http-java-client" 
creating branch 1.40.0-sp.2 as SHA f77608fbfb41410a8f62f40bc5a2df256c751d52
Creating a pull request
Creating a pull request with build: configure branch 1.40.0-sp.2 as a release branch
release-brancher create-pull-request

create a new release branch and send pull request to add release configuration

Options:
  --help          Show help                                            [boolean]
  --version       Show version number                                  [boolean]
  --branch-name   name of new branch to create               [string] [required]
  --target-tag    target tag                                 [string] [required]
  --release-type  release-please releaseType                            [string]
  --github-token  GitHub access token                        [string] [required]
  --repo          target repository                          [string] [required]

RequestError [HttpError]: Error creating Pull Request: Branch not found
    at /Users/suztomo/repo-automation-bots/packages/release-brancher/node_modules/@octokit/request/dist-node/index.js:86:21
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async getBranchHead (/Users/suztomo/repo-automation-bots/packages/release-brancher/node_modules/code-suggester/build/src/github/branch.js:37:25)
    at async Object.branch (/Users/suztomo/repo-automation-bots/packages/release-brancher/node_modules/code-suggester/build/src/github/branch.js:107:25)
    at async retry.retries (/Users/suztomo/repo-automation-bots/packages/release-brancher/node_modules/code-suggester/build/src/index.js:105:48)
    at async createPullRequest (/Users/suztomo/repo-automation-bots/packages/release-brancher/node_modules/code-suggester/build/src/index.js:105:24)
    at async Runner.createPullRequest (/Users/suztomo/repo-automation-bots/packages/release-brancher/build/src/release-brancher.js:209:16)
    at async Object.handler (/Users/suztomo/repo-automation-bots/packages/release-brancher/build/src/bin/commands/create-pull-request.js:62:9) {
  status: 404,
  response: {
    url: 'https://api.github.com/repos/suztomo/google-http-java-client/branches/main',
    status: 404,
    headers: {
      'access-control-allow-origin': '*',
      'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset',
      connection: 'close',
      'content-encoding': 'gzip',
      'content-security-policy': "default-src 'none'",
      'content-type': 'application/json; charset=utf-8',
      date: 'Tue, 28 Sep 2021 02:48:03 GMT',
      'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
      server: 'GitHub.com',
      'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
      'transfer-encoding': 'chunked',
      vary: 'Accept-Encoding, Accept, X-Requested-With',
      'x-accepted-oauth-scopes': '',
      'x-content-type-options': 'nosniff',
      'x-frame-options': 'deny',
      'x-github-media-type': 'github.v3; format=json',
      'x-github-request-id': 'E606:2E20:17E91F1:2C5E15E:61528262',
      'x-oauth-scopes': 'repo, workflow',
      'x-ratelimit-limit': '5000',
      'x-ratelimit-remaining': '4906',
      'x-ratelimit-reset': '1632799091',
      'x-ratelimit-resource': 'core',
      'x-ratelimit-used': '94',
      'x-xss-protection': '0'
    },
    data: {
      message: 'Branch not found',
      documentation_url: 'https://docs.github.com/rest/reference/repos#get-a-branch'
    }
  },
  request: {
    method: 'GET',
    url: 'https://api.github.com/repos/suztomo/google-http-java-client/branches/main',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit-rest.js/18.11.1 octokit-core.js/3.5.1 Node.js/15.14.0 (darwin; x64)',
      authorization: 'token [REDACTED]'
    },
    request: { hook: [Function: bound bound register] }
  }
}
```

Note that getting this failure takes several minutes because it retries. In the error, you see it tries to get `https://api.github.com/repos/suztomo/google-http-java-client/branches/main`.

I'm working on a pull request to fix this.

**Comment by suztomo** [comment]
I think this is related https://github.com/googleapis/code-suggester/pull/262/files
