### ISSUE TITLE
owlbot-python: post-processor crashing update lock jobs

### ISSUE THREAD

**Issue by chingor13** [googleapis/repo-automation-bots#2669]
Example: https://pantheon.corp.google.com/cloud-build/builds;region=global/ac2d4666-ba10-4b63-ba32-814d1083883b;step=9?project=repo-automation-bots

```
nox > Error while collecting sessions.
nox > Sessions not found: blacken
2021-10-06 18:34:29,870 synthtool [ERROR] > Failed executing nox -s blacken:
```

Example: https://pantheon.corp.google.com/cloud-build/builds;region=global/5d623c1a-fe62-459c-a405-676009704bf1;step=9?project=repo-automation-bots

```
Traceback (most recent call last):
  File "/usr/local/bin/nox", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/nox/__main__.py", line 45, in main
    exit_code = workflow.execute(
  File "/usr/local/lib/python3.9/site-packages/nox/workflow.py", line 49, in execute
    return_value = function_(*args, global_config=global_config)
  File "/usr/local/lib/python3.9/site-packages/nox/tasks.py", line 58, in load_nox_module
    check_nox_version(global_config.noxfile)
  File "/usr/local/lib/python3.9/site-packages/nox/_version.py", line 110, in check_nox_version
    needs_version = _read_needs_version(filename)
  File "/usr/local/lib/python3.9/site-packages/nox/_version.py", line 74, in _read_needs_version
    return _parse_needs_version(source, filename=filename)
  File "/usr/local/lib/python3.9/site-packages/nox/_version.py", line 55, in _parse_needs_version
    module: ast.Module = ast.parse(source, filename=filename)
  File "/usr/local/lib/python3.9/ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
  File "/workspace/python-logging/noxfile.py", line 91
    session.install("flask", "-c", constraints_path)session.install("webob", "-c", constraints_path)session.install("django", "-c", constraints_path)
                                                    ^
SyntaxError: invalid syntax
2021-10-06 17:34:09,693 synthtool [ERROR] > Failed executing nox -s blacken:
```

**Comment by parthea** [comment]
I have a fix for this in https://github.com/googleapis/synthtool/pull/1237
