### ISSUE TITLE
owl-bot-cli docker image is broken

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [googleapis/repo-automation-bots#3273]
```
$ docker run --rm -it gcr.io/repo-automation-bots/owlbot-cli:d5dd2b2218225d7857d369c36c6210cea1b289b5
Unable to find image 'gcr.io/repo-automation-bots/owlbot-cli:d5dd2b2218225d7857d369c36c6210cea1b289b5' locally
d5dd2b2218225d7857d369c36c6210cea1b289b5: Pulling from repo-automation-bots/owlbot-cli
59bf1c3509f3: Already exists 
39aa0d19fbe1: Pull complete 
f0b94cdce0f3: Pull complete 
664688b94c15: Pull complete 
970d3f55e459: Pull complete 
83d36481b6ff: Pull complete 
a8d26ca58465: Pull complete 
5417a992644d: Pull complete 
36eafe192a8b: Pull complete 
7894ec72364e: Pull complete 
Digest: sha256:f75fb8ba34260eb326e3f03575e5a0cc681c5e3fbda13c4581c595d55814c58e
Status: Downloaded newer image for gcr.io/repo-automation-bots/owlbot-cli:d5dd2b2218225d7857d369c36c6210cea1b289b5
internal/modules/cjs/loader.js:1102
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /usr/src/app/node_modules/node-fetch/src/index.js
require() of ES modules is not supported.
require() of /usr/src/app/node_modules/node-fetch/src/index.js from /usr/src/app/build/src/docker-api.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /usr/src/app/node_modules/node-fetch/package.json.

    at new NodeError (internal/errors.js:322:7)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1102:13)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/usr/src/app/build/src/docker-api.js:22:38)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32) {
  code: 'ERR_REQUIRE_ESM'
}
rennie@rennie:/google/src/cloud/rennie/kokoro-proj/google3/configs/cloud/gong/org_hierarchy/google.com/teams/cloud-devrel-teams/project.cloud-devrel-release-resources$ 
```

**Comment by SurferJeffAtGoogle** [comment]
I suspect https://github.com/googleapis/repo-automation-bots/commit/4a7e26283f12e5b6ea487f7460e3a1b2790d9b59
