### ISSUE TITLE
sync-repo-settings' tests are failing

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [googleapis/repo-automation-bots#3415]
```
PS C:\Users\rennie\gitrepos\repo-automation-bots\packages\sync-repo-settings> git status
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
PS C:\Users\rennie\gitrepos\repo-automation-bots\packages\sync-repo-settings> git log -1
commit 7d96dc8461db2ef9f43787a8b57bb8034bf97153 (HEAD -> main, origin/main)
Author: Takashi Matsuo <tmatsuo@google.com>
Date:   Mon Apr 11 15:16:42 2022 -0700

    chore(owl-bot): change the routing to Cloud Run backend (#3412)

    towards #3318
PS C:\Users\rennie\gitrepos\repo-automation-bots\packages\sync-repo-settings> npm test

> sync-repo-settings@0.0.1 pretest C:\Users\rennie\gitrepos\repo-automation-bots\packages\sync-repo-settings
> npm run compile


> sync-repo-settings@0.0.1 compile C:\Users\rennie\gitrepos\repo-automation-bots\packages\sync-repo-settings
> tsc


> sync-repo-settings@0.0.1 test C:\Users\rennie\gitrepos\repo-automation-bots\packages\sync-repo-settings
> cross-env LOG_LEVEL=fatal c8 mocha build/test



  Sync repo settings
"schedule.repository" is not a known webhook name (https://developer.github.com/v3/activity/events/types/)
{"severity":"DEBUG","level":20,"message":"file: .github/sync-repo-settings.yaml"}
    ✔ should not create a failing status check for a real world config(java) (125ms)
"schedule.repository" is not a known webhook name (https://developer.github.com/v3/activity/events/types/)
{"severity":"DEBUG","level":20,"message":"file: .github/sync-repo-settings.yaml"}
    ✔ should not create a failing status check for a real world config(python) (50ms)
"schedule.repository" is not a known webhook name (https://developer.github.com/v3/activity/events/types/)
{"severity":"DEBUG","level":20,"message":"file: .github/sync-repo-settings.yaml"}
    ✔ should not create a failing status check for a real world config(python library)
"schedule.repository" is not a known webhook name (https://developer.github.com/v3/activity/events/types/)
{"severity":"DEBUG","level":20,"message":"file: .github/sync-repo-settings.yaml"}
    ✔ should create a failing status check for a broken config (121ms)

  getConfig
    compatibility tests
      ✔ should read a real world config(java)
      ✔ should read a real world config(python)

  SyncRepoSettings
    ✔ should fill in default values
    ✔ should fill in default values from the repo
    ✔ should handle multiple branches

  Sync repo settings
"schedule.repository" is not a known webhook name (https://developer.github.com/v3/activity/events/types/)
    ✔ should skip for the wrong context
"schedule.repository" is not a known webhook name (https://developer.github.com/v3/activity/events/types/)
    ✔ should ignore repos not represented in required-checks.json
"schedule.repository" is not a known webhook name (https://developer.github.com/v3/activity/events/types/)
    ✔ should update settings for a known repository
"schedule.repository" is not a known webhook name (https://developer.github.com/v3/activity/events/types/)
    ✔ should nope out if github returns no languages
"schedule.repository" is not a known webhook name (https://developer.github.com/v3/activity/events/types/)
    ✔ should use localized config if available
"schedule.repository" is not a known webhook name (https://developer.github.com/v3/activity/events/types/)
    ✔ should use localized config and skip branch protection
"schedule.repository" is not a known webhook name (https://developer.github.com/v3/activity/events/types/)
{"severity":"DEBUG","level":20,"message":"file: .github/sync-repo-settings.yaml"}
    ✔ should detect a valid schema
"schedule.repository" is not a known webhook name (https://developer.github.com/v3/activity/events/types/)
{"severity":"DEBUG","level":20,"message":"file: .github/sync-repo-settings.yaml"}
    ✔ should detect an invalid schema (40ms)
"schedule.repository" is not a known webhook name (https://developer.github.com/v3/activity/events/types/)
{"severity":"DEBUG","level":20,"message":"file: .github/sync-repo-settings.yaml"}
    ✔ should detect invalid yaml in the schema (44ms)
"schedule.repository" is not a known webhook name (https://developer.github.com/v3/activity/events/types/)
    ✔ should not sync settings for pushes with no changes to the config
"schedule.repository" is not a known webhook name (https://developer.github.com/v3/activity/events/types/)
    ✔ should not sync settings for pushes to non-default branches
"schedule.repository" is not a known webhook name (https://developer.github.com/v3/activity/events/types/)
    ✔ should sync settings for pushes that modify the config
"schedule.repository" is not a known webhook name (https://developer.github.com/v3/activity/events/types/)
    ✔ should sync settings for a newly transferred repo

  cli
Missing required argument: github-token
    ✔ should throw if no token is available
    ✔ loads github-token from environment (38ms)
    ✔ should run remote configuration (46ms)
    ✔ should run local configuration

  Sync repo settings
    1) "before each" hook for "should ignore repos in ignored repos in required-checks.json"


  26 passing (1s)
  1 failing

  1) Sync repo settings
       "before each" hook for "should ignore repos in ignored repos in required-checks.json":
     Error: [@octokit/auth-app] appId option is required
      at Object.createAppAuth (node_modules\@octokit\auth-app\dist-node\index.js:492:11)
          -> C:\Users\rennie\gitrepos\repo-automation-bots\packages\sync-repo-settings\node_modules\@octokit\auth-app\dist-src\index.js:11:15
      at getState (node_modules\octokit-auth-probot\dist-node\index.js:188:21)
          -> C:\Users\rennie\gitrepos\repo-automation-bots\packages\sync-repo-settings\node_modules\octokit-auth-probot\dist-src\get-state.js:19:19
      at createProbotAuth (node_modules\octokit-auth-probot\dist-node\index.js:203:17)
          -> C:\Users\rennie\gitrepos\repo-automation-bots\packages\sync-repo-settings\node_modules\octokit-auth-probot\dist-src\index.js:5:19
      at new Octokit (node_modules\@octokit\core\dist-node\index.js:113:20)
          -> C:\Users\rennie\gitrepos\repo-automation-bots\packages\sync-repo-settings\node_modules\@octokit\core\dist-src\index.js:69:26
      at new _a (node_modules\@octokit\core\dist-node\index.js:167:30)
          -> C:\Users\rennie\gitrepos\repo-automation-bots\packages\sync-repo-settings\node_modules\@octokit\core\dist-src\index.js:117:34
      at new OctokitWithDefaults (node_modules\@octokit\core\dist-node\index.js:143:11)
          -> C:\Users\rennie\gitrepos\repo-automation-bots\packages\sync-repo-settings\node_modules\@octokit\core\dist-src\index.js:96:21
      at new OctokitWithDefaults (node_modules\@octokit\core\dist-node\index.js:143:11)
          -> C:\Users\rennie\gitrepos\repo-automation-bots\packages\sync-repo-settings\node_modules\@octokit\core\dist-src\index.js:96:21
      at new Probot (node_modules\probot\lib\probot.js:38:25)
          -> C:\Users\rennie\gitrepos\repo-automation-bots\packages\sync-repo-settings\node_modules\probot\src\probot.ts:74:21
      at Object.createProbot (node_modules\probot\lib\create-probot.js:54:12)
          -> C:\Users\rennie\gitrepos\repo-automation-bots\packages\sync-repo-settings\node_modules\probot\src\create-probot.ts:73:10
      at Context.<anonymous> (build\test\test.js:118:27)
          -> C:\Users\rennie\gitrepos\repo-automation-bots\packages\sync-repo-settings\test\test.ts:114:14
      at processImmediate (internal/timers.js:461:21)



-----------------------|---------|----------|---------|---------|-------------------------
File                   | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
-----------------------|---------|----------|---------|---------|-------------------------
All files              |   91.72 |    85.48 |     100 |   91.72 | 
 bot.ts                |    97.2 |    83.33 |     100 |    97.2 | 70-71,77-78
 cli.ts                |   98.01 |       80 |     100 |   98.01 | 100-101
 config.ts             |     100 |      100 |     100 |     100 | 
 sync-repo-settings.ts |   86.73 |    88.23 |     100 |   86.73 | 193-203,241-255,284-298
-----------------------|---------|----------|---------|---------|-------------------------
npm ERR! Test failed.  See above for more details.
```

**Comment by SurferJeffAtGoogle** [comment]
I'm nonplussed because the top of the stack is reported as 

```
C:\Users\rennie\gitrepos\repo-automation-bots\packages\sync-repo-settings\test\test.ts:114:14
```

but that file doesn't exist:

```
    Directory: C:\Users\rennie\gitrepos\repo-automation-bots\packages\sync-repo-settings\test


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        9/30/2021  12:43 PM                fixtures
-a----        8/24/2021   1:40 PM           5738 compatibility-test.ts
-a----        8/24/2021   1:40 PM           4415 sync-repo-settings.ts
-a----        1/11/2022  12:30 PM          14408 test-bot.ts
-a----        9/13/2021   8:55 AM           4112 test-cli.ts
```

**Comment by chingor13** [comment]
I can't reproduce this. Is it still happening for you @SurferJeffAtGoogle?
