### ISSUE TITLE
owlbot: scan-googleapis-gen-and-create-pull-requests receives 422 opening PRs

### ISSUE THREAD

**Issue by bcoe** [googleapis/repo-automation-bots#3427]
Error logs:

```
status: 422,
Step #3:     at async Object.handler (/usr/src/app/build/src/bin/commands/scan-googleapis-gen-and-create-pull-requests.js:78:9) {
Step #3:     at async scanGoogleapisGenAndCreatePullRequests (/usr/src/app/build/src/scan-googleapis-gen-and-create-pull-requests.js:138:9)
Step #3:     at async copyCodeAndAppendOrCreatePullRequest (/usr/src/app/build/src/copy-code.js:386:18)
Step #3:     at async createPullRequestFromLastCommit (/usr/src/app/build/src/create-pr.js:116:18)
Step #3:     at processTicksAndRejections (internal/process/task_queues.js:95:5)
Step #3:     at runMicrotasks (<anonymous>)
Step #3:     at /usr/src/app/node_modules/@octokit/request/dist-node/index.js:86:21
Step #3: RequestError [HttpError]: Validation Failed: {"resource":"PullRequest","code":"custom","message":"A pull request already exists for googleapis:owl-bot-copy."}
```

Job in question:

https://pantheon.corp.google.com/cloud-build/builds;region=global/2f03bbd1-5562-4607-981d-e335dee2b794?project=repo-automation-bots

**Comment by SurferJeffAtGoogle** [comment]
Seems to have been a temporary hiccup.  The past 100 runs have succeeded.
