### ISSUE TITLE
auto-label: receiving unhandled rejection applying label to java-cloud-bom

### ISSUE THREAD

**Issue by bcoe** [googleapis/repo-automation-bots#3429]
Auto-label is crashing with the following exception for `java-cloud-bom`:

```bash
Info
2022-04-13 12:01:15.351 PDTauto_labelup7trjuszhbn Request size label added to PR #4109 in googleapis/java-cloud-bom, label is "size: u"
Info
2022-04-13 12:01:15.351 PDTauto_labelup7trjuszhbn {action: {…}, count: 1, event: unknown, level: 30, trigger: {…}, type: metric}
Info
2022-04-13 12:01:15.351 PDTauto_labelup7trjuszhbn {action: {…}, count: 1, event: unknown, level: 30, trigger: {…}, type: metric}
Default
2022-04-13 12:01:15.898 PDTauto_labelup7trjuszhbn Unhandled rejection
Default
2022-04-13 12:01:15.898 PDTauto_labelup7trjuszhbn HttpError: Label does not exist
Default
2022-04-13 12:01:15.898 PDTauto_labelup7trjuszhbn at /workspace/node_modules/@octokit/request/dist-node/index.js:86:21
Default
2022-04-13 12:01:15.898 PDTauto_labelup7trjuszhbn at runMicrotasks (<anonymous>)
Default
2022-04-13 12:01:15.898 PDTauto_labelup7trjuszhbn at processTicksAndRejections (internal/process/task_queues.js:97:5)
Default
2022-04-13 12:01:15.898 PDTauto_labelup7trjuszhbn at async sendRequestWithRetries (/workspace/node_modules/@octokit/auth-app/dist-node/index.js:466:12)
Debug
2022-04-13 12:01:15.932 PDTauto_labelup7trjuszhbn Function execution took 2642 ms. Finished with status: crash
```

The logs can be found with the ID: `up7trjuszhbn`.

**Comment by chingor13** [comment]
Fixed in #3431
