### ISSUE TITLE
owl-bot has Firebase errors

### ISSUE THREAD

**Issue by tmatsuo** [googleapis/repo-automation-bots#3460]
The log:

FirebaseAppError: The default Firebase app already exists. This means you called initializeApp() more than once without providing an app name as the second argument. In most cases you only need to call initializeApp() once. But if you do want to initialize multiple apps, pass a second argument to initializeApp() to give each app a unique name. at FirebaseAppError.FirebaseError [as constructor]

**Comment by tmatsuo** [comment]
It happens number of times with concurrent requests in Cloud Run.

More detailed logs:

FirebaseAppError: The default Firebase app already exists. This means you called initializeApp() more than once without providing an app name as the second argument. In most cases you only need to call initializeApp() once. But if you do want to initialize multiple apps, pass a second argument to initializeApp() to give each app a unique name.
    at FirebaseAppError.FirebaseError [as constructor] (/usr/src/app/node_modules/firebase-admin/lib/utils/error.js:44:28)
    at FirebaseAppError.PrefixedFirebaseError [as constructor] (/usr/src/app/node_modules/firebase-admin/lib/utils/error.js:90:28)
    at new FirebaseAppError (/usr/src/app/node_modules/firebase-admin/lib/utils/error.js:125:28)
    at AppStore.initializeApp (/usr/src/app/node_modules/firebase-admin/lib/app/lifecycle.js:42:23)
    at FirebaseNamespaceInternals.initializeApp (/usr/src/app/node_modules/firebase-admin/lib/app/firebase-namespace.js:43:33)
    at FirebaseNamespace.initializeApp (/usr/src/app/node_modules/firebase-admin/lib/app/firebase-namespace.js:311:30)
    at Object.OwlBot (/usr/src/app/build/src/owl-bot.js:86:34)
    at bootstrap.server.maxRetries (/usr/src/app/build/src/server-backend.js:28:22)
    at async GCFBootstrapper.loadProbot (/usr/src/app/node_modules/gcf-utils/build/src/gcf-utils.js:165:9)
    at async /usr/src/app/node_modules/gcf-utils/build/src/gcf-utils.js:309:33 {

**Comment by tmatsuo** [comment]
I think this is a race condition among multiple requests around the server startup. I think we can avoid this by initializing the firestore db in server-backend.ts.
