### ISSUE TITLE
blunderbuss: Error: 3 INVALID_ARGUMENT: transaction required

### ISSUE THREAD

**Issue by chingor13** [googleapis/repo-automation-bots#3929]
From the logs:

```
Error: 3 INVALID_ARGUMENT: transaction required
    at Object.callErrorFromStatus (/workspace/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
    at Object.onReceiveStatus (/workspace/node_modules/@grpc/grpc-js/build/src/client.js:189:52)
    at Object.onReceiveStatus (/workspace/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:365:141)
    at Object.onReceiveStatus (/workspace/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:328:181)
    at /workspace/node_modules/@grpc/grpc-js/build/src/call-stream.js:187:78
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
```

**Comment by SurferJeffAtGoogle** [comment]
Is this a recurring issue?
