### ISSUE TITLE
owlbot: Owlbot-cli is broken

### ISSUE THREAD

**Issue by Neenu1995** [googleapis/repo-automation-bots#4019]
Running owlbot-cli locally is broken with the following [error message](https://screenshot.googleplex.com/4CSFK3axhLv6pcT).
```
Error: Command failed: git config --global --add safe.directory /googleapis-gen
error: could not lock config file //.gitconfig: Permission denied

    at checkExecSyncError (child_process.js:790:11)
    at Object.execSync (child_process.js:863:15)
    at cmd (/usr/src/app/build/src/cmd.js:44:29)
    at toLocalRepo (/usr/src/app/build/src/copy-code.js:590:9)
    at copyCode (/usr/src/app/build/src/copy-code.js:619:23)
    at Object.handler (/usr/src/app/build/src/bin/commands/copy-code.js:59:40) {
  status: 255,
  signal: null,
  output: [
    null,
    <Buffer >,
    <Buffer 65 72 72 6f 72 3a 20 63 6f 75 6c 64 20 6e 6f 74 20 6c 6f 63 6b 20 63 6f 6e 66 69 67 20 66 69 6c 65 20 2f 2f 2e 67 69 74 63 6f 6e 66 69 67 3a 20 50 65 ... 16 more bytes>
  ],
  pid: 17,
  stdout: <Buffer >,
  stderr: <Buffer 65 72 72 6f 72 3a 20 63 6f 75 6c 64 20 6e 6f 74 20 6c 6f 63 6b 20 63 6f 6e 66 69 67 20 66 69 6c 65 20 2f 2f 2e 67 69 74 63 6f 6e 66 69 67 3a 20 50 65 ... 16 more bytes>
}

```

**Comment by bcoe** [comment]
I did some bisection with the containers that have been built, and was able to unblock Neenu by using a container from 14 days ago.
