### ISSUE TITLE
flakybot dies with "Process exited with code 16"

### ISSUE THREAD

**Issue by tmatsuo** [googleapis/repo-automation-bots#4076]
The log:

> "Error: Process exited with code 16
    at process.<anonymous> (/layers/google.nodejs.functions-framework/functions-framework/node_modules/@google-cloud/functions-framework/build/src/invoker.js:92:22)
    at process.emit (events.js:400:28)
    at process.emit (domain.js:475:12)
    at process.exit (internal/process/per_thread.js:179:15)
    at sendCrashResponse (/layers/google.nodejs.functions-framework/functions-framework/node_modules/@google-cloud/functions-framework/build/src/logger.js:44:9)
    at process.<anonymous> (/layers/google.nodejs.functions-framework/functions-framework/node_modules/@google-cloud/functions-framework/build/src/invoker.js:88:44)
    at process.emit (events.js:400:28)
    at process.emit (domain.js:475:12)
    at processPromiseRejections (internal/process/promises.js:245:33)
    at processTicksAndRejections (internal/process/task_queues.js:96:32)"

**Comment by chingor13** [comment]
The underlying crash:

```
Error: 4 DEADLINE_EXCEEDED: Deadline expired before operation could complete.
    at Object.callErrorFromStatus (/workspace/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
    at Object.onReceiveStatus (/workspace/node_modules/@grpc/grpc-js/build/src/client.js:189:52)
    at Object.onReceiveStatus (/workspace/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:365:141)
    at Object.onReceiveStatus (/workspace/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:328:181)
    at /workspace/node_modules/@grpc/grpc-js/build/src/call-stream.js:187:78
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
```

It's unclear where it's actually failing.

**Comment by tmatsuo** [comment]
My guess is that it's happening during the datastore lock operation. Anyways, if this happens when there is a burst of Pub/Sub message, we can introduce flow control in the serverless proxy.

Downgrading because this error should be recoverable.

**Comment by tmatsuo** [comment]
Let's close this until we see it happening again frequently
