### ISSUE TITLE
"Server Error" in release-trigger-backend

### ISSUE THREAD

**Issue by tmatsuo** [googleapis/repo-automation-bots#4389]
To see the actual log, use the following query:

insertId="63209f80000be356a956d205"

The stack trace:

> "HttpError: Server Error
    at /home/node/node_modules/@octokit/request/dist-node/index.js:88:21
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async sendRequestWithRetries (/home/node/node_modules/@octokit/auth-app/dist-node/index.js:376:12)
    at async Object.next (/home/node/node_modules/@octokit/plugin-paginate-rest/dist-node/index.js:71:28)
    at async findPendingReleasePullRequests (/home/node/build/src/release-trigger.js:103:22)
    at async /home/node/build/src/bot.js:311:37
    at async Promise.all (index 0)
    at async /home/node/node_modules/gcf-utils/build/src/gcf-utils.js:387:25"
status: 502
type: "RequestError"

**Comment by SurferJeffAtGoogle** [comment]
I tried searching with that query and found 0 entries.  Is this a one-time issue or does it repeat?

**Comment by tmatsuo** [comment]
I saw it at least 2 times, but not very often. I sent you a direct link to the log offline.

**Comment by tmatsuo** [comment]
Here is the query you can use for seeing the log.
```
resource.type = "cloud_run_revision"
resource.labels.service_name = "release-trigger-backend"
resource.labels.location = "us-central1"
 severity>="ERROR"
 timestamp >= "2022-09-16T19:23:03.463038Z"
```

It's not frequent and recoverable, so I'm closing this
