### ISSUE TITLE
Error: Not Found

### ISSUE THREAD

**Issue by chingor13** [googleapis/repo-automation-bots#4470]
Error group: `CInRy6vKpIOFcQ`

Stack trace:
```
HttpError: Not Found
    at /usr/src/app/node_modules/@octokit/request/dist-node/index.js:88:21
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async sendRequestWithRetries (/usr/src/app/node_modules/@octokit/auth-app/dist-node/index.js:376:12)
    at async /usr/src/app/node_modules/release-please/build/src/github.js:156:30
    at async GitHub.getPullRequest (/usr/src/app/node_modules/release-please/build/src/github.js:1063:20)
    at async /usr/src/app/node_modules/release-please/build/src/github.js:148:20
    at async GitHub.createPullRequest (/usr/src/app/node_modules/release-please/build/src/github.js:1063:20)
    at async GitHub.createReleasePullRequest (/usr/src/app/node_modules/release-please/build/src/github.js:954:16)
    at async Manifest.createOrUpdatePullRequest (/usr/src/app/node_modules/release-please/build/src/manifest.js:491:32)
caused by: HttpError: Not Found
    at /usr/src/app/node_modules/@octokit/request/dist-node/index.js:88:21
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async sendRequestWithRetries (/usr/src/app/node_modules/@octokit/auth-app/dist-node/index.js:376:12)
    at async /usr/src/app/node_modules/release-please/build/src/github.js:156:30
    at async GitHub.getPullRequest (/usr/src/app/node_modules/release-please/build/src/github.js:1063:20)
    at async /usr/src/app/node_modules/release-please/build/src/github.js:148:20
    at async GitHub.createPullRequest (/usr/src/app/node_modules/release-please/build/src/github.js:1063:20)
    at async GitHub.createReleasePullRequest (/usr/src/app/node_modules/release-please/build/src/github.js:954:16)
    at async Manifest.createOrUpdatePullRequest (/usr/src/app/node_modules/release-please/build/src/manifest.js:491:32)
```

**Comment by chingor13** [comment]
Note, this is happening on a non-Google repo and appears to be the call to fetch the created pull request after it's been opened. Perhaps pull requests are disabled on the repository this is running on?

**Comment by tmatsuo** [comment]
Maybe there was a force push into the HEAD branch? The commit in the previous state will be lost.

**Comment by tmatsuo** [comment]
One of the repo is https://github.com/googleworkspace/apps-script-oauth2
Maybe we can work with them (workspace team) to know more.
