### ISSUE TITLE
Error: `Failed to download the diff: HTTP error, status code: 403`

### ISSUE THREAD

**Issue by chingor13** [googleapis/repo-automation-bots#4476]
Stack trace:

```
Error: Failed to download the diff: HTTP error, status code: 403
    at parseRegionTagsInPullRequest (/workspace/build/src/region-tag-parser.js:56:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async scanPullRequest (/workspace/build/src/snippet-bot.js:166:20)
    at async /workspace/build/src/snippet-bot.js:657:9
    at async Promise.all (index 0)
    at async /workspace/node_modules/gcf-utils/build/src/gcf-utils.js:389:25
```

Occurred on `pull_request.opened` for https://github.com/googleapis/google-cloud-java/pull/8438 (a very large merge PR with "infinite" files changed in the UI).

**Comment by tmatsuo** [comment]
dup of #4442
