### ISSUE TITLE
Error: `Cannot read property 'nodes' of null`

### ISSUE THREAD

**Issue by chingor13** [googleapis/repo-automation-bots#4477]
Stack trace:

```
TypeError: Cannot read property 'nodes' of null
    at GitHub.mergeCommitsGraphQL (/usr/src/app/node_modules/release-please/build/src/github.js:574:49)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async GitHub.mergeCommitIterator (/usr/src/app/node_modules/release-please/build/src/github.js:477:30)
    at async Manifest.buildPullRequests (/usr/src/app/node_modules/release-please/build/src/manifest.js:253:26)
    at async Manifest.createPullRequests (/usr/src/app/node_modules/release-please/build/src/manifest.js:418:39)
    at async Function.Runner.createPullRequests (/usr/src/app/build/src/runner.js:23:5)
    at async runBranchConfiguration (/usr/src/app/build/src/release-please.js:230:5)
    at async runBranchConfigurationWithConfigurationHandling (/usr/src/app/build/src/release-please.js:163:9)
    at async /usr/src/app/build/src/release-please.js:373:13
```

**Comment by suztomo** [comment]
Release Please in google-cloud-java repository seems being impacted. Thank you for troubleshooting.
