### ISSUE TITLE
Error: `Service Unavailable`

### ISSUE THREAD

**Issue by chingor13** [googleapis/repo-automation-bots#4480]
Stack trace:

```
Error: Service Unavailable
    at Gaxios._request (/usr/src/app/node_modules/gaxios/build/src/gaxios.js:130:23)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Compute.requestAsync (/usr/src/app/node_modules/google-auth-library/build/src/auth/oauth2client.js:368:18)
    at async Upload.makeRequest (/usr/src/app/node_modules/@google-cloud/storage/build/src/resumable-upload.js:556:21)
    at async retry.retries (/usr/src/app/node_modules/@google-cloud/storage/build/src/resumable-upload.js:306:29)
    at async Upload.createURIAsync (/usr/src/app/node_modules/@google-cloud/storage/build/src/resumable-upload.js:303:21)
```

This looks like gcf-utils trying to upload the payload to GCS.

**Comment by tmatsuo** [comment]
Unfortunately the webhook will be lost in this case imo.

**Comment by tmatsuo** [comment]
One mitigation I came up with is to upload the payload to gcs only when the playload is too big for Cloud Task instead of always uploading it to gcs.

**Comment by tmatsuo** [comment]
I applied #4703 to snippet-bot on Dec 2nd and the bot has been working ok. Also there is literally zero request which exceeds the limit.

So it turned out that we had been always uploading to gcs only for very exceptional cases.

**Comment by tmatsuo** [comment]
We configure the renovate bot to automatically update the dependencies with 30 stability days. I expect the renovate bot will automatically update to gcf-utils 14.4.0 or higher in early January. I'll close this once it happens.
