### ISSUE TITLE
Error: `3 INVALID_ARGUMENT: Invalid transaction.`

### ISSUE THREAD

**Issue by chingor13** [googleapis/repo-automation-bots#4481]
Stack trace:

```
Error: 3 INVALID_ARGUMENT: Invalid transaction.
    at Object.callErrorFromStatus (/usr/src/app/node_modules/@grpc/grpc-js/build/src/call.js:31:19)
    at Object.onReceiveStatus (/usr/src/app/node_modules/@grpc/grpc-js/build/src/client.js:190:52)
    at Object.onReceiveStatus (/usr/src/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:365:141)
    at Object.onReceiveStatus (/usr/src/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:328:181)
    at /usr/src/app/node_modules/@grpc/grpc-js/build/src/call-stream.js:188:78
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
for call at
    at ServiceClientImpl.makeUnaryRequest (/usr/src/app/node_modules/@grpc/grpc-js/build/src/client.js:160:30)
    at ServiceClientImpl.<anonymous> (/usr/src/app/node_modules/@grpc/grpc-js/build/src/make-client.js:105:19)
    at /usr/src/app/node_modules/@google-cloud/firestore/build/src/v1/firestore_client.js:206:29
    at /usr/src/app/node_modules/@google-cloud/firestore/node_modules/google-gax/build/src/normalCalls/timeout.js:44:16
    at repeat (/usr/src/app/node_modules/@google-cloud/firestore/node_modules/google-gax/build/src/normalCalls/retries.js:80:25)
    at /usr/src/app/node_modules/@google-cloud/firestore/node_modules/google-gax/build/src/normalCalls/retries.js:118:13
    at OngoingCallPromise.call (/usr/src/app/node_modules/@google-cloud/firestore/node_modules/google-gax/build/src/call.js:67:27)
    at NormalApiCaller.call (/usr/src/app/node_modules/@google-cloud/firestore/node_modules/google-gax/build/src/normalCalls/normalApiCaller.js:34:19)
    at /usr/src/app/node_modules/@google-cloud/firestore/node_modules/google-gax/build/src/createApiCall.js:81:30
```

**Comment by tmatsuo** [comment]
Same as #4486, I think

**Comment by tmatsuo** [comment]
The system recovers, so downgraded to p3
