### ISSUE TITLE
Error: `3 INVALID_ARGUMENT: transaction required`

### ISSUE THREAD

**Issue by chingor13** [googleapis/repo-automation-bots#4486]
Stack trace:

```
Error: 3 INVALID_ARGUMENT: transaction required
    at Object.callErrorFromStatus (/workspace/node_modules/@grpc/grpc-js/build/src/call.js:31:19)
    at Object.onReceiveStatus (/workspace/node_modules/@grpc/grpc-js/build/src/client.js:190:52)
    at Object.onReceiveStatus (/workspace/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:365:141)
    at Object.onReceiveStatus (/workspace/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:328:181)
    at /workspace/node_modules/@grpc/grpc-js/build/src/call-stream.js:188:78
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
for call at
    at ServiceClientImpl.makeUnaryRequest (/workspace/node_modules/@grpc/grpc-js/build/src/client.js:160:30)
    at ServiceClientImpl.<anonymous> (/workspace/node_modules/@grpc/grpc-js/build/src/make-client.js:105:19)
    at /workspace/node_modules/@google-cloud/datastore/build/src/v1/datastore_client.js:181:29
    at /workspace/node_modules/google-gax/build/src/normalCalls/timeout.js:44:16
    at OngoingCall.call (/workspace/node_modules/google-gax/build/src/call.js:67:27)
    at NormalApiCaller.call (/workspace/node_modules/google-gax/build/src/normalCalls/normalApiCaller.js:34:19)
    at /workspace/node_modules/google-gax/build/src/createApiCall.js:84:30
```

**Comment by tmatsuo** [comment]
I think this happens when it fails to start the datastore transaction. It will very likely be recovered.

Potentially it is better to catch this (check the transaction object is undefined) and somehow return HTTP 503, but it's a cleanup task, imo.

**Comment by SurferJeffAtGoogle** [comment]
Closing because the system recovers.
