### ISSUE TITLE
Cherrypick bot reported a merge conflict.

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [googleapis/repo-automation-bots#4501]
The log line says "Merge conflict" and nothing more.

**Comment by tmatsuo** [comment]
Stack trace:

```
HttpError: Merge conflict
    at /usr/src/app/node_modules/@octokit/request/dist-node/index.js:88:21
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async sendRequestWithRetries (/usr/src/app/node_modules/@octokit/auth-app/dist-node/index.js:376:12)
    at async Object.cherryPickCommits (/usr/src/app/build/src/cherry-pick.js:162:72)
    at async cherryPickAsPullRequest (/usr/src/app/build/src/cherry-pick.js:82:25)
    at async /usr/src/app/build/src/bot.js:97:9
    at async Promise.all (index 0)
    at async /usr/src/app/node_modules/gcf-utils/build/src/gcf-utils.js:389:25
```
