### ISSUE TITLE
sync_repo_settings reports "Resource not accessible by integration"

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [googleapis/repo-automation-bots#4502]
No other details in the log.

**Comment by tmatsuo** [comment]
If you click the `view logs` link in the error group detail, you see the log entry. You can expand the log entry (jsonpayload->err->stack), then you get the stack trace. In this case, we got:

```
HttpError: Resource not accessible by integration
    at /workspace/node_modules/@octokit/request/dist-node/index.js:88:21
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async sendRequestWithRetries (/workspace/node_modules/@octokit/auth-app/dist-node/index.js:376:12)
    at async Object.next (/workspace/node_modules/@octokit/plugin-paginate-rest/dist-node/index.js:71:28)
    at async findOpenIssueByCreator (/workspace/node_modules/@google-automations/issue-utils/build/src/issue-utils.js:30:25)
    at async addOrUpdateIssue (/workspace/node_modules/@google-automations/issue-utils/build/src/issue-utils.js:68:20)
    at async handleConfigurationError (/workspace/build/src/bot.js:166:23)
    at async /workspace/build/src/bot.js:100:20
    at async Promise.all (index 0)
```

**Comment by codyoss** [comment]
This is no longer used.
