### ISSUE TITLE
owl-bot-backend encountered "Error: Command failed: git clone --depth 10 ..."

### ISSUE THREAD

**Issue by tmatsuo** [googleapis/repo-automation-bots#4527]
stack:

> Error: Command failed: git clone --depth 10 https://github.com/googleapis/python-documentai-toolbox.git python-documentai-toolbox
Cloning into 'python-documentai-toolbox'...
fatal: could not read Username for 'https://github.com': Input/output error

>    at checkExecSyncError (child_process.js:790:11)
    at Object.execSync (child_process.js:863:15)
    at cmd (/usr/src/app/build/src/cmd.js:44:29)
    at fetchConfigs (/usr/src/app/build/src/fetch-configs.js:60:9)
    at refreshConfigs (/usr/src/app/build/src/handlers.js:214:80)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async /usr/src/app/build/src/owl-bot.js:208:9
    at async Promise.all (index 0)
    at async /usr/src/app/node_modules/gcf-utils/build/src/gcf-utils.js:389:25

**Comment by SurferJeffAtGoogle** [comment]
It's a private repo.
