### ISSUE TITLE
release-please-backend dies with "You have exceeded a secondary rate limit."

### ISSUE THREAD

**Issue by tmatsuo** [googleapis/repo-automation-bots#4528]
It's recoverable, but it should be caught by gcf-utils then returns HTTP 503

stack:

> HttpError: You have exceeded a secondary rate limit. Please wait a few minutes before you try again.
    at /usr/src/app/node_modules/@octokit/request/dist-node/index.js:88:21
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async sendRequestWithRetries (/usr/src/app/node_modules/@octokit/auth-app/dist-node/index.js:376:12)
    at async /usr/src/app/node_modules/release-please/build/src/github.js:71:38
    at async GitHub.graphqlRequest (/usr/src/app/node_modules/release-please/build/src/github.js:1083:20)
    at async GitHub.mergeCommitsGraphQL (/usr/src/app/node_modules/release-please/build/src/github.js:549:26)
    at async GitHub.mergeCommitIterator (/usr/src/app/node_modules/release-please/build/src/github.js:477:30)
    at async latestReleaseVersion (/usr/src/app/node_modules/release-please/build/src/manifest.js:882:22)
    at async Function.fromConfig (/usr/src/app/node_modules/release-please/build/src/manifest.js:153:31)
caused by: HttpError: You have exceeded a secondary rate limit. Please wait a few minutes before you try again.
    at /usr/src/app/node_modules/@octokit/request/dist-node/index.js:88:21
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async sendRequestWithRetries (/usr/src/app/node_modules/@octokit/auth-app/dist-node/index.js:376:12)
    at async /usr/src/app/node_modules/release-please/build/src/github.js:71:38
    at async GitHub.graphqlRequest (/usr/src/app/node_modules/release-please/build/src/github.js:1083:20)
    at async GitHub.mergeCommitsGraphQL (/usr/src/app/node_modules/release-please/build/src/github.js:549:26)
    at async GitHub.mergeCommitIterator (/usr/src/app/node_modules/release-please/build/src/github.js:477:30)
    at async latestReleaseVersion (/usr/src/app/node_modules/release-please/build/src/manifest.js:882:22)
    at async Function.fromConfig (/usr/src/app/node_modules/release-please/build/src/manifest.js:153:31)

**Comment by chingor13** [comment]
In #4873, we now only report this on the final attempt. Cloud Tasks should back off so hopefully it should complete on a retry
