### ISSUE TITLE
snippet-bot got "Invalid request. Only 65535 characters are allowed; 65581 were supplied."

### ISSUE THREAD

**Issue by tmatsuo** [googleapis/repo-automation-bots#4529]
stack:

> HttpError: Invalid request.

> Only 65535 characters are allowed; 65581 were supplied.
    at /workspace/node_modules/@octokit/request/dist-node/index.js:88:21
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async sendRequestWithRetries (/workspace/node_modules/@octokit/auth-app/dist-node/index.js:376:12)
    at async CheckAggregator.submit (/workspace/build/src/utils.js:160:13)
    at async scanPullRequest (/workspace/build/src/snippet-bot.js:445:5)
    at async /workspace/build/src/snippet-bot.js:657:9
    at async Promise.all (index 0)
    at async /workspace/node_modules/gcf-utils/build/src/gcf-utils.js:389:25

**Comment by tmatsuo** [comment]
I'm baffled why this happens. The bot cuts at 64000 and adds some footer which should not exceeds this limit.

**Comment by tmatsuo** [comment]
Oh wait it is `CheckAggregator.submit`. Somehow I thought it was about the comment.
