### ISSUE TITLE
release-please got an authorization error

### ISSUE THREAD

**Issue by tmatsuo** [googleapis/repo-automation-bots#4538]
It seems non-google org.

stack (some parts reducted):

> HttpError: Although you appear to have the correct authorization credentials, the `xxxxxxx` organization has an IP allow list enabled, and xxx.xxx.xxx.xxx is not permitted to access this resource.
    at /usr/src/app/node_modules/@octokit/request/dist-node/index.js:88:21
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async sendRequestWithRetries (/usr/src/app/node_modules/@octokit/auth-app/dist-node/index.js:376:12)
    at async getConfig (/usr/src/app/node_modules/@google-automations/bot-config-utils/build/src/bot-config-utils.js:343:22)
    at async /usr/src/app/build/src/release-please.js:424:37
    at async Promise.all (index 0)
    at async /usr/src/app/node_modules/gcf-utils/build/src/gcf-utils.js:389:25

**Comment by chingor13** [comment]
This was an external org, and this is rare. We can ignore this unless it becomes a bigger problem
