### ISSUE TITLE
release-please-backend got 'Invalid request. "sha" wasn't supplied'.

### ISSUE THREAD

**Issue by tmatsuo** [googleapis/repo-automation-bots#4620]
Stack:

```
HttpError: Invalid request.

"sha" wasn't supplied.
    at /usr/src/app/node_modules/@octokit/request/dist-node/index.js:88:21
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async sendRequestWithRetries (/usr/src/app/node_modules/@octokit/auth-app/dist-node/index.js:376:12)
    at async GitHub.createFileOnNewBranch (/usr/src/app/node_modules/release-please/build/src/github.js:1097:40)
    at async FilePullRequestOverflowHandler.handleOverflow (/usr/src/app/node_modules/release-please/build/src/util/pull-request-overflow-handler.js:49:25)
    at async /usr/src/app/node_modules/release-please/build/src/github.js:205:19
    at async GitHub.updatePullRequest (/usr/src/app/node_modules/release-please/build/src/github.js:1221:20)
    at async Manifest.maybeUpdateExistingPullRequest (/usr/src/app/node_modules/release-please/build/src/manifest.js:527:36)
    at async Manifest.createOrUpdatePullRequest (/usr/src/app/node_modules/release-please/build/src/manifest.js:495:20)
caused by: HttpError: Invalid request.

"sha" wasn't supplied.
    at /usr/src/app/node_modules/@octokit/request/dist-node/index.js:88:21
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async sendRequestWithRetries (/usr/src/app/node_modules/@octokit/auth-app/dist-node/index.js:376:12)
    at async GitHub.createFileOnNewBranch (/usr/src/app/node_modules/release-please/build/src/github.js:1097:40)
    at async FilePullRequestOverflowHandler.handleOverflow (/usr/src/app/node_modules/release-please/build/src/util/pull-request-overflow-handler.js:49:25)
    at async /usr/src/app/node_modules/release-please/build/src/github.js:205:19
    at async GitHub.updatePullRequest (/usr/src/app/node_modules/release-please/build/src/github.js:1221:20)
    at async Manifest.maybeUpdateExistingPullRequest (/usr/src/app/node_modules/release-please/build/src/manifest.js:527:36)
    at async Manifest.createOrUpdatePullRequest (/usr/src/app/node_modules/release-please/build/src/manifest.js:495:20)
```

**Comment by tmatsuo** [comment]
Rare occurrence, downgrading

**Comment by chingor13** [comment]
We haven't seen this in a long time -- likely a temporal issue that is resolved by our retries
