### ISSUE TITLE
release-please-backend received "Path prefixes must be unique: /compute/metadata/, /compute/"

### ISSUE THREAD

**Issue by tmatsuo** [googleapis/repo-automation-bots#4632]
Stack:

```
Error: Path prefixes must be unique: /compute/metadata/, /compute/
    at new CommitSplit (/usr/src/app/node_modules/release-please/build/src/util/commit-split.js:48:31)
    at Manifest.buildPullRequests (/usr/src/app/node_modules/release-please/build/src/manifest.js:295:20)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Manifest.createPullRequests (/usr/src/app/node_modules/release-please/build/src/manifest.js:418:39)
    at async Function.Runner.createPullRequests (/usr/src/app/build/src/runner.js:23:5)
    at async runBranchConfiguration (/usr/src/app/build/src/release-please.js:231:5)
    at async runBranchConfigurationWithConfigurationHandling (/usr/src/app/build/src/release-please.js:164:9)
    at async /usr/src/app/build/src/release-please.js:270:13
    at async Promise.all (index 0)
```

**Comment by chingor13** [comment]
Turns out this is blocking google-cloud-go by throwing an error which stops the other release-please configs from running. It's unclear why this is explicitly disallowed, so we will just fix the commit splitter to handle overlapping paths (returning the deepest matching path).
