### ISSUE TITLE
[Owl Bot bootstrapper] Can you provide URL of the log upon failure?

### ISSUE THREAD

**Issue by suztomo** [googleapis/repo-automation-bots#4668]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

 **Is your feature request related to a problem? Please describe.**

I ran owlbot bootstrapper. It said it failed and check log. But I cannot tell where is the log:

```
suztomo@suztomo:~/google-cloud-java$ C=1ee4f0eed30c
suztomo@suztomo:~/google-cloud-java$ bootstrapper run-trigger pre-process   --apiId=apikeys   --language=java   --languageContainer=$C   --repoToClone=git@github.com:googleapis/google-cloud-java.git --skipIssueOnFailure
bootstrapper run-trigger

Kicks off the build trigger for owlbot-bootstrapper

Options:
  --help                    Show help                                  [boolean]
  --version                 Show version number                        [boolean]
  --projectId               project ID which contains the build file
                                     [string] [default: "owlbot-bootstrap-prod"]
  --triggerId               trigger of build to run
                               [string] [default: "owlbot-bootstrapper-trigger"]
  --apiId                   api ID to generate a library for [string] [required]
  --repoToClone             monorepo to clone                           [string]
  --language                language for which to generate a library
                                                             [string] [required]
  --installationId          Github app installation ID
                                                  [string] [default: "25330619"]
  --container               common container image                      [string]
  --languageContainer       language-specific container image           [string]
  --monoRepoDir             path to the directory in which the mono repo will be
                            cloned                                      [string]
  --serviceConfigPath       path to save the service config file        [string]
  --interContainerVarsPath  path to save the inter container variables  [string]
  --skipIssueOnFailure      does not create issues if failure
                                                      [boolean] [default: false]

GoogleError: Build failed; check build logs for details
    at Operation._unpackResponse (/usr/local/google/home/suztomo/repo-automation-bots/packages/owlbot-bootstrapper/cli/node_modules/google-gax/build/src/longRunningCalls/longrunning.js:142:31)
    at /usr/local/google/home/suztomo/repo-automation-bots/packages/owlbot-bootstrapper/cli/node_modules/google-gax/build/src/longRunningCalls/longrunning.js:122:18 {
  code: 2
```

 **Describe the solution you'd like**

Upon an error in Google Cloud Build, it's nice to show the URL of the log:

```
Build failed. Please check logs for details: http://...
```

 **Describe alternatives you've considered**

Nothing particular

 **Additional context**

@sofisl is helping me to onboard bootstrapper

**Comment by suztomo** [comment]
Memo: Sofia knows the correct URL to check the log.
