### ISSUE TITLE
[release-brancher] release-brancher fails for google-cloud-java monorepo

### ISSUE THREAD

**Issue by suztomo** [googleapis/repo-automation-bots#4726]
I ran release-brancher for google-cloud-java repository for its v1.0.0 tag for 1.0.x branch. It failed:

```
suztomo@suztomo:/tmp$ release-brancher create-pull-request \
  --branch-name="1.0.x" \
  --target-tag="v1.0.0" \
  --repo="googleapis/google-cloud-java" \
  --pull-request-title="feat: next release from main branch is 1.1.0" \
  --release-type=java-backport
creating branch 1.0.x as SHA be5da900e288b204721a068488f85454560487fc
release-brancher create-pull-request

create a new release branch and send pull request to add release configuration

Options:
  --help                Show help                                      [boolean]
  --version             Show version number                            [boolean]
  --branch-name         name of new branch to create         [string] [required]
  --target-tag          target tag                           [string] [required]
  --release-type        release-please releaseType                      [string]
  --github-token        GitHub access token
                               [string] [required] [default: (from-environment)]
  --repo                target repository                    [string] [required]
  --pull-request-title  commit message and the title of the pull request against
                        default branch                                  [string]

RequestError [HttpError]: Reference update failed
    at /usr/local/google/home/suztomo/.nvm/versions/node/v16.14.2/lib/node_modules/@google-cloud/release-brancher/node_modules/@octokit/request/dist-node/index.js:86:21
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Runner.createBranch (/usr/local/google/home/suztomo/.nvm/versions/node/v16.14.2/lib/node_modules/@google-cloud/release-brancher/build/src/release-brancher.js:107:26)
    at async Object.handler (/usr/local/google/home/suztomo/.nvm/versions/node/v16.14.2/lib/node_modules/@google-cloud/release-brancher/build/src/bin/commands/create-pull-request.js:67:9) {
  status: 422,
  response: {
    url: 'https://api.github.com/repos/googleapis/google-cloud-java/git/refs',
    status: 422,
    headers: {
      'access-control-allow-origin': '*',
      'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset',
      connection: 'close',
      'content-length': '121',
      'content-security-policy': "default-src 'none'",
      'content-type': 'application/json; charset=utf-8',
      date: 'Mon, 05 Dec 2022 22:23:10 GMT',
      'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
      server: 'GitHub.com',
      'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
      vary: 'Accept-Encoding, Accept, X-Requested-With',
      'x-accepted-oauth-scopes': 'repo',
      'x-content-type-options': 'nosniff',
      'x-frame-options': 'deny',
      'x-github-api-version-selected': '2022-11-28',
      'x-github-media-type': 'github.v3; format=json',
      'x-github-request-id': '8AC2:72DF:37110:70D6F:638E6F4E',
      'x-oauth-scopes': 'repo, workflow',
      'x-ratelimit-limit': '5000',
      'x-ratelimit-remaining': '4991',
      'x-ratelimit-reset': '1670282174',
      'x-ratelimit-resource': 'core',
      'x-ratelimit-used': '9',
      'x-xss-protection': '0'
    },
    data: {
      message: 'Reference update failed',
      documentation_url: 'https://docs.github.com/rest/reference/git#create-a-reference'
    }
  },
  request: {
    method: 'POST',
    url: 'https://api.github.com/repos/googleapis/google-cloud-java/git/refs',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit-rest.js/18.12.0 octokit-core.js/3.6.0 Node.js/16.14.2 (linux; x64)',
      authorization: 'token [REDACTED]',
      'content-type': 'application/json; charset=utf-8'
    },
    body: '{"ref":"refs/heads/1.0.x","sha":"be5da900e288b204721a068488f85454560487fc"}',
    request: { hook: [Function: bound bound register] }
  }
}

```

**Comment by SurferJeffAtGoogle** [comment]
@suztomo Do you have a work-around?  Is this blocking your work?
