### ISSUE TITLE
auto-approve dies with "Cannot read property 'name' of null"

### ISSUE THREAD

**Issue by tmatsuo** [googleapis/repo-automation-bots#4764]
The stack trace:

```
TypeError: Cannot read property 'name' of null
    at /workspace/build/src/auto-approve.js:165:52
    at /workspace/node_modules/probot/node_modules/@octokit/webhooks/dist-node/index.js:177:14
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Promise.all (index 0)
    at async /workspace/node_modules/gcf-utils/build/src/gcf-utils.js:390:25
```

**Comment by chingor13** [comment]
We haven't seen this in the last 30 days. Closing for now.
