### ISSUE TITLE
release-trigger: The bot did not mark the release as published or successful

### ISSUE THREAD

**Issue by Neenu1995** [googleapis/repo-automation-bots#4978]
Triggered a [release](https://github.com/googleapis/java-bigquerystorage/pull/1994) from java-bigquerystorage. The release job was triggered by the bot. It was [successful](https://screenshot.googleplex.com/3Jmg4hHamt2fDZj) but the bot [did not report](https://screenshot.googleplex.com/7THLeVA5BhEhAYh) it back in the PR.

**Comment by chingor13** [comment]
It's currently the release job's duty to report pass/fail status back to the PR. Unfortunately, the release-trigger bot does not have access to the release job status.

From the logs:

```
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.9.13/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/.pyenv/versions/3.9.13/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/.pyenv/versions/3.9.13/lib/python3.9/site-packages/releasetool/__main__.py", line 213, in <module>
    main()
  File "/root/.pyenv/versions/3.9.13/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/root/.pyenv/versions/3.9.13/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/root/.pyenv/versions/3.9.13/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/.pyenv/versions/3.9.13/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/.pyenv/versions/3.9.13/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/root/.pyenv/versions/3.9.13/lib/python3.9/site-packages/releasetool/__main__.py", line 193, in publish_reporter_finish
    releasetool.commands.publish_reporter.finish(github_token, pr, status, details)
  File "/root/.pyenv/versions/3.9.13/lib/python3.9/site-packages/releasetool/commands/publish_reporter.py", line 131, in finish
    github_token = releasetool.github.GitHubToken.token_from_dict(
  File "/root/.pyenv/versions/3.9.13/lib/python3.9/site-packages/releasetool/github.py", line 83, in token_from_dict
    access_token = get_installation_access_token(
  File "/root/.pyenv/versions/3.9.13/lib/python3.9/site-packages/releasetool/github.py", line 106, in get_installation_access_token
    private_key = default_backend().load_pem_private_key(private_key_bytes, None)
TypeError: load_pem_private_key() missing 1 required positional argument: 'unsafe_skip_rsa_key_validation'
```

I think there's a breaking change from python's cryptography package from v38 -> v39 which may have been merged in your repo.

**Comment by chingor13** [comment]
Please update your releasetool version to 1.10.5 to fix
