### ISSUE TITLE
owlbot: scan and create PRs job fails on bad checkouts

### ISSUE THREAD

**Issue by codyoss** [googleapis/repo-automation-bots#5358]
I have sometimes observed the following error. From build `35c3dece-74b8-4676-9f9d-06a219b792ed`:

```text
2024-06-21T00:53:24.117Z git checkout -t origin/owl-bot-copy-apis-Google_Cloud_SecurityCenterManagement_V1
fatal: 'origin/owl-bot-copy-apis-Google_Cloud_SecurityCenterManagement_V1' is not a commit and a branch 'owl-bot-copy-apis-Google_Cloud_SecurityCenterManagement_V1' cannot be created from it
owl-bot.js scan-googleapis-gen-and-create-pull-requests

...

Error: Command failed: git checkout -t origin/owl-bot-copy-apis-Google_Cloud_SecurityCenterManagement_V1
fatal: 'origin/owl-bot-copy-apis-Google_Cloud_SecurityCenterManagement_V1' is not a commit and a branch 'owl-bot-copy-apis-Google_Cloud_SecurityCenterManagement_V1' cannot be created from it
    at findAndAppendPullRequest (/usr/src/app/build/src/copy-code.js:280:5)
    at async copyCodeAndAppendOrCreatePullRequest (/usr/src/app/build/src/copy-code.js:368:15)
    at async scanGoogleapisGenAndCreatePullRequests (/usr/src/app/build/src/scan-googleapis-gen-and-create-pull-requests.js:146:13)
    at async Object.handler (/usr/src/app/build/src/bin/commands/scan-googleapis-gen-and-create-pull-requests.js:97:9)
```

**Comment by meltsufin** [comment]
@codyoss Are you still seeing this issue?

**Comment by codyoss** [comment]
I don't think I have looked since filling. This was not observable from the outside, but I think I noticed this from looking at Cloud Build dashboards and logs. Feel free to close this if it is no longer happening. I think a lot has likely changed since I filed this.
