### ISSUE TITLE
Error: Error updating ref heads/release-please ... Changes must be made through a pull request.

### ISSUE THREAD

**Issue by burkedavison** [googleapis/repo-automation-bots#5551]
```
message: "Error updating ref heads/release-please--branches--main--components--memorystore-cluster-autoscaler to 6e330a5c7c239124c9ffb7fd8c0803085815aa26: Changes must be made through a pull request."
stack: "Error: Error updating ref heads/release-please--branches--main--components--memorystore-cluster-autoscaler to 6e330a5c7c239124c9ffb7fd8c0803085815aa26
    at updateRef (/usr/src/app/node_modules/code-suggester/build/src/github/commit-and-push.js:113:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async commitAndPush (/usr/src/app/node_modules/code-suggester/build/src/github/commit-and-push.js:138:5)
    at async createPullRequest (/usr/src/app/node_modules/code-suggester/build/src/index.js:140:5)
    at async /usr/src/app/node_modules/release-please/build/src/github.js:148:30
    at async GitHub.createPullRequest (/usr/src/app/node_modules/release-please/build/src/github.js:1247:20)
    at async Manifest.createOrUpdatePullRequest (/usr/src/app/node_modules/release-please/build/src/manifest.js:553:32)
    at async Promise.all (index 0)
    at async Manifest.createPullRequests (/usr/src/app/node_modules/release-please/build/src/manifest.js:493:33)
    at async Runner.createPullRequests (/usr/src/app/build/src/runner.js:23:5)
caused by: HttpError: Changes must be made through a pull request.
    at /usr/src/app/node_modules/@octokit/request/dist-node/index.js:122:21
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async sendRequestWithRetries (/usr/src/app/node_modules/@octokit/auth-app/dist-node/index.js:398:12)
    at async updateRef (/usr/src/app/node_modules/code-suggester/build/src/github/commit-and-push.js:103:9)
    at async commitAndPush (/usr/src/app/node_modules/code-suggester/build/src/github/commit-and-push.js:138:5)
    at async createPullRequest (/usr/src/app/node_modules/code-suggester/build/src/index.js:140:5)
    at async /usr/src/app/node_modules/release-please/build/src/github.js:148:30
    at async GitHub.createPullRequest (/usr/src/app/node_modules/release-please/build/src/github.js:1247:20)
    at async Manifest.createOrUpdatePullRequest (/usr/src/app/node_modules/release-please/build/src/manifest.js:553:32)
    at async Promise.all (index 0)"
```

**Comment by meltsufin** [comment]
@chingor13 Does this look like a real issue?

**Comment by chingor13** [comment]
Looks like the branch they configured is protected by GitHub rules. We won't be fixing this.
