### ISSUE TITLE
Cron jobs cannot use context.repo()

### ISSUE THREAD

**Issue by chingor13** [googleapis/repo-automation-bots#643]
The release-please bot is using cron to trigger snapshot builds. The main logic reads the config file from `.github/release-please.yml` and uses `context.config(<filename>)` to load the configuration. This method requires payload.repository.owner to be present.

It's not entirely clear what is provided in the context for scheduled tasks.

```
{
  "textPayload": "TypeError: Cannot read property 'login' of undefined\n    at Context.repo (/workspace/node_modules/probot/lib/context.js:107:31)\n    at Context.<anonymous> (/workspace/node_modules/probot/lib/context.js:192:39)\n    at step (/workspace/node_modules/probot/lib/context.js:33:23)\n    at Object.next (/workspace/node_modules/probot/lib/context.js:14:53)",
  "insertId": "000001-6c89e7ac-880d-4e63-b8e5-2b64378af760",
  "resource": {
    "type": "cloud_function",
    "labels": {
      "function_name": "release_please",
      "project_id": "repo-automation-bots",
      "region": "us-central1"
    }
  },
  "timestamp": "2020-07-01T23:05:55.574Z",
  "severity": "ERROR",
  "labels": {
    "execution_id": "xza5kjg7w99m"
  },
  "logName": "projects/repo-automation-bots/logs/cloudfunctions.googleapis.com%2Fcloud-functions",
  "trace": "projects/repo-automation-bots/traces/9f38f8148e3546ca1914cc25eb61ee57",
  "receiveTimestamp": "2020-07-01T23:05:57.850815449Z"
}
```

**Comment by bcoe** [comment]
this should now be fixed.
