### ISSUE TITLE
bug(snippet-bot): 500 "INVALID_ARGUMENT: Task size too large"

### ISSUE THREAD

**Issue by tmatsuo** [googleapis/repo-automation-bots#893]
Copied from the Cloud function logging UI:
```
{
 insertId: "000000-93725394-f99c-4720-ad18-ebf90d96236f"  
 jsonPayload: {
  code: 3   
  details: "Task size too large"   
  level: 50   
  message: "3 INVALID_ARGUMENT: Task size too large"   
  metadata: {
   internalRepr: {
   }
   options: {
   }
  }
  stack: "Error: 3 INVALID_ARGUMENT: Task size too large
    at Object.callErrorFromStatus (/workspace/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
    at Object.onReceiveStatus (/workspace/node_modules/@grpc/grpc-js/build/src/client.js:176:52)
    at Object.onReceiveStatus (/workspace/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:342:141)
    at Object.onReceiveStatus (/workspace/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:305:181)
    at process.nextTick (/workspace/node_modules/@grpc/grpc-js/build/src/call-stream.js:124:78)
    at process._tickCallback (internal/process/next_tick.js:61:11)"   
  type: "Error"   
 }
 labels: {
  execution_id: "jdxenjbdqt4t"   
 }
 logName: "projects/repo-automation-bots/logs/cloudfunctions.googleapis.com%2Fcloud-functions"  
 receiveTimestamp: "2020-08-21T20:37:31.461117240Z"  
 resource: {
  labels: {
   function_name: "snippet_bot"    
   project_id: "repo-automation-bots"    
   region: "us-central1"    
  }
  type: "cloud_function"   
 }
 severity: "ERROR"  
 timestamp: "2020-08-21T20:37:24.306Z"  
 trace: "projects/repo-automation-bots/traces/3ccabd5b462f061a1b2075f7d264ccd0"  
}
```

**Comment by tmatsuo** [comment]
We haven't seen this for a long time.
